import { StyleSheet } from "react-native";

import { colors } from "@/constants/Colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundSecondary },
  content: { paddingBottom: 36, position: "relative" },
  backdrop: {
    height: 700,
  },
  heroCard: {
    margin: 16,
    marginBottom: 14,
    padding: 18,
    borderRadius: 28,
    backgroundColor: "rgba(54,94,130,0.94)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    elevation: 3,
    overflow: "hidden",
  },
  heroOrbLarge: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.12)",
    top: -56,
    right: -24,
  },
  heroOrbSmall: {
    position: "absolute",
    width: 118,
    height: 118,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    bottom: -30,
    left: -18,
  },
  heroOrbWarm: {
    position: "absolute",
    width: 144,
    height: 144,
    borderRadius: 999,
    backgroundColor: "rgba(255,194,116,0.12)",
    bottom: -20,
    right: 28,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  backButton: { padding: 8, borderRadius: 999 },
  iconButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.96 }],
  },
  title: { fontSize: 24, fontWeight: "700", color: colors.textWhite },
  heroHeadline: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "800",
    color: colors.textWhite,
    marginBottom: 10,
    maxWidth: "88%",
  },
  heroCopy: {
    fontSize: 14,
    lineHeight: 21,
    color: "rgba(255,255,255,0.82)",
    marginBottom: 16,
    maxWidth: "92%",
  },
  catalogButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  softPressed: {
    opacity: 0.94,
    transform: [{ scale: 0.985 }],
  },
  catalogButtonText: {
    color: colors.textWhite,
    fontSize: 13,
    fontWeight: "700",
  },
  searchCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginHorizontal: 16,
    marginBottom: 10,
    borderRadius: 20,
    padding: 16,
    backgroundColor: "rgba(255,255,255,0.68)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 2,
  },
  searchBody: { flex: 1 },
  searchGlyph: {
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primaryLight,
  },
  label: { fontSize: 14, fontWeight: "700", color: colors.textSecondary, marginBottom: 4 },
  searchHint: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.textMuted,
  },
  searchInputCard: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 18,
    paddingHorizontal: 14,
    backgroundColor: "rgba(255,255,255,0.82)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.95)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  input: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 16,
    color: colors.textPrimary,
  },
  clearButton: {
    paddingLeft: 10,
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginHorizontal: 16,
    marginBottom: 18,
  },
  metaPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.62)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.85)",
  },
  metaPillText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 18,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.textSecondary,
  },
  emptyGlassCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 18,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.66)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
    alignItems: "flex-start",
    gap: 8,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  emptyBody: {
    fontSize: 13,
    lineHeight: 19,
    color: colors.textMuted,
  },
  emptyBodyStrong: {
    color: colors.textSecondary,
    fontWeight: "700",
  },
  glassResultCard: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 16,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.94)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.09,
    shadowRadius: 12,
    elevation: 2,
  },
  softPressedCard: {
    opacity: 0.94,
    transform: [{ scale: 0.988 }],
  },
  resultIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 999,
    backgroundColor: colors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  resultInfo: {
    flex: 1,
    marginRight: 10,
  },
  resultName: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  resultMeta: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 4,
  },
  resultBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
  },
  sourceBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: colors.infoLight,
    borderWidth: 1,
    borderColor: colors.infoBorder,
  },
  sourceBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.info,
  },
  aiBadge: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.infoBorder,
  },
  aiBadgeText: {
    color: colors.primaryDark,
  },
  onboardButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primaryDark,
    marginHorizontal: 16,
    marginTop: 2,
    marginBottom: 22,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 3,
    gap: 8,
  },
  onboardButtonDisabled: { opacity: 0.5 },
  onboardButtonText: { color: colors.white, fontSize: 16, fontWeight: "600" },
  inlineCatalogButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.primaryLight,
  },
  inlineCatalogButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.primaryDark,
  },
  categoryScroll: {
    marginBottom: 12,
  },
  categoryScrollContent: {
    gap: 8,
    paddingHorizontal: 16,
    paddingRight: 24,
  },
  categoryChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.62)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
  },
  categoryChipActive: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.infoBorder,
  },
  chipPressed: {
    opacity: 0.94,
    transform: [{ scale: 0.985 }],
  },
  categoryChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  categoryChipTextActive: {
    color: colors.primaryDark,
  },
  browseCard: {
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 16,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.68)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  browseTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  browseCategoryPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: colors.badgeYellowLight,
  },
  browseCategoryPillText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.warningDark,
  },
  browseSourceText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  browseName: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 6,
  },
  browseStatus: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  featuresCard: {
    marginHorizontal: 16,
    marginTop: 4,
    padding: 18,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.7)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  featureGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 14,
  },
  featureTile: {
    width: "48%",
    minHeight: 88,
    borderRadius: 18,
    padding: 14,
    backgroundColor: "rgba(240,244,248,0.78)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.85)",
  },
  featureIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 999,
    backgroundColor: colors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  featureLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textSecondary,
    lineHeight: 18,
  },
});
