import { StyleSheet } from "react-native";

import { colors } from "@/constants/Colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundSecondary },
  content: { paddingBottom: 24, position: "relative" },
  backdrop: { top: -48, height: 1260 },
  form: { paddingHorizontal: 16, gap: 18 },
  label: { fontSize: 14, fontWeight: "600", color: colors.textSecondary, marginTop: 8 },
  input: {
    backgroundColor: "rgba(248,251,255,0.84)",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 15,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
  },
  inputMultiline: { height: 72, textAlignVertical: "top" },
  pickerScreen: { flex: 1, backgroundColor: colors.backgroundSecondary },
  pickerBackdrop: { top: -42, height: 920 },
  pickerShell: { flex: 1, paddingHorizontal: 16, paddingBottom: 18 },
  pickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "rgba(255,255,255,0.68)",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 2,
  },
  pickerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(244,248,251,0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
  },
  pickerTitleWrap: { flex: 1, paddingHorizontal: 12 },
  pickerEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: colors.textMuted,
    marginBottom: 2,
  },
  pickerTitle: { fontSize: 17, fontWeight: "700", color: colors.textPrimary },
  pickerDoneButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: "rgba(236,244,250,0.92)",
  },
  pickerDoneText: { fontSize: 14, fontWeight: "700", color: colors.primaryDark },
  pickerBody: { flex: 1, paddingTop: 16 },
  overviewCard: {
    marginHorizontal: 4,
    padding: 22,
    borderRadius: 28,
    backgroundColor: "rgba(43,77,111,0.94)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    elevation: 4,
    overflow: "hidden",
  },
  overviewGlow: {
    position: "absolute",
    width: 170,
    height: 170,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.1)",
    top: -44,
    right: -8,
  },
  overviewEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.66)",
  },
  overviewTitle: {
    fontSize: 22,
    lineHeight: 30,
    fontWeight: "800",
    color: colors.textWhite,
    marginTop: 8,
    maxWidth: "82%",
  },
  overviewStats: { flexDirection: "row", gap: 12, marginTop: 18 },
  overviewStat: {
    minWidth: 88,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  overviewStatValue: { fontSize: 20, fontWeight: "700", color: colors.textWhite },
  overviewStatLabel: { fontSize: 11, color: "rgba(255,255,255,0.72)", marginTop: 4 },
  formCard: {
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.68)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 2,
  },
  exerciseSection: { gap: 10 },
  exercisesHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  sectionEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    color: colors.textMuted,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.textPrimary,
    marginTop: 3,
  },
  addExBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 16,
    backgroundColor: "rgba(238,245,250,0.92)",
    borderWidth: 1,
    borderColor: "rgba(104,138,160,0.18)",
  },
  addExText: { fontSize: 14, fontWeight: "700", color: colors.primaryDark },
  exerciseCard: {
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    elevation: 2,
  },
  exerciseCardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  exerciseCardTitleRow: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
  exerciseNumBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(237,245,252,0.92)",
  },
  exerciseNum: { fontSize: 13, fontWeight: "700", color: colors.primaryDark },
  exerciseTitleBlock: { flex: 1, gap: 2 },
  exerciseName: { fontSize: 16, fontWeight: "700", color: colors.textPrimary },
  exerciseSubtitle: { fontSize: 12, color: colors.textMuted },
  exerciseActions: { flexDirection: "row", gap: 8, marginLeft: 12 },
  iconAction: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(244,248,251,0.92)",
  },
  iconActionDanger: { backgroundColor: "rgba(253,241,241,0.92)" },
  targetsRow: { flexDirection: "row", gap: 8, marginTop: 14 },
  targetField: { flex: 1 },
  targetLabel: { fontSize: 11, color: colors.textMuted, marginBottom: 6, marginLeft: 4 },
  targetInput: {
    backgroundColor: "rgba(248,251,255,0.92)",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.textPrimary,
    textAlign: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
  },
  emptyExercises: {
    backgroundColor: "rgba(255,255,255,0.62)",
    borderRadius: 24,
    padding: 32,
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    borderStyle: "dashed",
  },
  emptyIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(237,245,252,0.94)",
  },
  emptyTitle: { fontSize: 17, fontWeight: "700", color: colors.textPrimary },
  emptyText: { fontSize: 14, color: colors.textMuted, textAlign: "center", lineHeight: 20 },
  footer: { paddingTop: 2, paddingBottom: 8 },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primaryDark,
    borderRadius: 18,
    paddingVertical: 16,
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 3,
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { fontSize: 16, fontWeight: "600", color: colors.textWhite },
  softPressed: { transform: [{ scale: 0.992 }], opacity: 0.95 },
  buttonPressed: { transform: [{ scale: 0.992 }], opacity: 0.95 },
});
