import { StyleSheet } from "react-native";

import { colors } from "@/constants/Colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundSecondary },
  content: { paddingBottom: 24, position: "relative" },
  backdrop: { top: -48, height: 1200 },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.backgroundSecondary,
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.76)",
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 12,
  },
  metricRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  metricIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  metricLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textSecondary,
    width: 52,
  },
  ratingRow: {
    flex: 1,
    flexDirection: "row",
    gap: 4,
  },
  ratingDot: {
    flex: 1,
    height: 20,
    borderRadius: 4,
    backgroundColor: "rgba(230,236,242,0.8)",
  },
  ratingValue: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.textPrimary,
    width: 22,
    textAlign: "right",
  },
  chipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  symptomChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 12,
    backgroundColor: "rgba(243,247,251,0.9)",
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  symptomChipActive: {
    backgroundColor: colors.accentLight,
    borderColor: colors.accent,
  },
  symptomText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  symptomTextActive: {
    color: colors.accent,
  },
  notesInput: {
    backgroundColor: "rgba(248,251,255,0.84)",
    borderRadius: 14,
    padding: 14,
    fontSize: 14,
    color: colors.textPrimary,
    lineHeight: 20,
    minHeight: 100,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: colors.primaryDark,
    borderRadius: 18,
    paddingVertical: 14,
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 3,
  },
  saveButtonPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.995 }],
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.white,
  },
  avgGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  avgBadge: {
    flexBasis: "22%",
    alignItems: "center",
    backgroundColor: "rgba(248,251,255,0.84)",
    borderRadius: 14,
    padding: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
  },
  avgValue: {
    fontSize: 18,
    fontWeight: "700",
  },
  avgLabel: {
    fontSize: 11,
    color: colors.gray,
    marginTop: 2,
  },
  entryCount: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 12,
  },
  freqChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "rgba(243,247,251,0.9)",
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  freqText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  historyRow: {
    padding: 12,
    borderRadius: 16,
    backgroundColor: "rgba(248,251,255,0.72)",
    marginTop: 10,
  },
  historyDate: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  historyMetrics: {
    flexDirection: "row",
    gap: 12,
    marginTop: 6,
  },
  miniMetric: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  miniValue: {
    fontSize: 12,
    fontWeight: "700",
  },
  historySymptoms: {
    fontSize: 12,
    color: colors.gray,
    marginTop: 4,
  },
  historyNotes: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 4,
    lineHeight: 18,
  },
  spacer: {
    height: 24,
  },
});
