import { StyleSheet } from "react-native";

import { colors } from "@/constants/Colors";

export const catalogDetailStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundSecondary },
  content: { paddingBottom: 24, position: "relative" },
  backdrop: { top: -48 },
  centered: { flex: 1, justifyContent: "center", alignItems: "center" },
  missingText: { color: colors.textSecondary, fontSize: 15 },
  section: { paddingHorizontal: 16, marginTop: 16 },
  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 2,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.68)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
  },
  chipText: { fontSize: 12, fontWeight: "600", color: colors.textSecondary },
  chipSuccess: { backgroundColor: "rgba(236,246,240,0.92)", borderColor: "rgba(95,156,120,0.14)" },
  chipSuccessText: { fontSize: 12, fontWeight: "700", color: colors.success, textTransform: "capitalize" },
  chipWarm: { backgroundColor: "rgba(255,244,230,0.92)", borderColor: "rgba(241,181,104,0.18)" },
  chipWarmText: { fontSize: 12, fontWeight: "700", color: colors.warningDark },
  chipInfo: { gap: 6, backgroundColor: "rgba(236,245,252,0.92)", borderColor: "rgba(104,138,160,0.14)" },
  chipInfoText: { fontSize: 12, fontWeight: "700", color: colors.primaryDark },
  card: {
    borderRadius: 26,
    padding: 20,
    backgroundColor: "rgba(255,255,255,0.7)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 2,
  },
  cardDanger: { backgroundColor: "rgba(255,246,246,0.86)", borderColor: "rgba(203,91,91,0.12)" },
  sectionEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    color: colors.textMuted,
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.grayDark,
    marginBottom: 12,
  },
  bodyText: {
    fontSize: 15,
    lineHeight: 24,
    color: colors.textSecondary,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  tag: {
    backgroundColor: "rgba(236,245,252,0.94)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(104,138,160,0.18)",
  },
  tagText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.primaryDarker,
  },
  detailStack: { gap: 14 },
  detailItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "rgba(248,251,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
  },
  detailContent: { flex: 1 },
  detailLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  detailValue: {
    fontSize: 15,
    fontWeight: "500",
    color: colors.textPrimary,
    marginTop: 1,
    lineHeight: 21,
  },
  noteBox: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: "rgba(236,245,252,0.94)",
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(104,138,160,0.18)",
  },
  noteText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 22,
    color: colors.primaryDarker,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primaryDark,
    paddingVertical: 16,
    borderRadius: 18,
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 3,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "700",
  },
  buttonPressed: { transform: [{ scale: 0.992 }], opacity: 0.95 },
  bottomSpacer: { height: 32 },
});
