"""Add user_preferences and peptide tables

Revision ID: e5e80fb951ad
Revises: 
Create Date: 2026-04-09 12:16:27.891029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

from app.database import UUID

# revision identifiers, used by Alembic.
revision: str = 'e5e80fb951ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('longevity', 'metabolic', 'hormonal', 'cardiovascular', 'cognitive', 'dermatological', 'anti_inflammatory', 'antimicrobial', 'other', name='medication_category_enum'), nullable=False),
    sa.Column('form', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_profile', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_profile_version', sa.Integer(), nullable=False),
    sa.Column('ai_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_name'), 'medications', ['name'], unique=False)
    op.create_table('peptides',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('research', 'therapeutic', 'cosmetic', 'performance', 'recovery', 'other', name='peptide_category_enum'), nullable=False),
    sa.Column('form', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goals', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('mechanism_tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_profile', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_profile_version', sa.Integer(), nullable=False),
    sa.Column('ai_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peptides_name'), 'peptides', ['name'], unique=False)
    op.create_table('user_medications',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('user_id', UUID(), nullable=False),
    sa.Column('medication_id', UUID(), nullable=False),
    sa.Column('dosage_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('dosage_unit', sa.String(length=30), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'twice_daily', 'three_times_daily', 'weekly', 'every_other_day', 'as_needed', name='frequency_enum'), nullable=False),
    sa.Column('take_window', sa.Enum('morning_fasted', 'morning_with_food', 'midday', 'afternoon', 'evening', 'bedtime', name='take_window_enum'), nullable=False),
    sa.Column('with_food', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_medications_user_id'), 'user_medications', ['user_id'], unique=False)
    op.create_table('user_peptides',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('user_id', UUID(), nullable=False),
    sa.Column('peptide_id', UUID(), nullable=False),
    sa.Column('dosage_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('dosage_unit', sa.String(length=30), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'twice_daily', 'three_times_daily', 'weekly', 'every_other_day', 'as_needed', name='frequency_enum'), nullable=False),
    sa.Column('take_window', sa.Enum('morning_fasted', 'morning_with_food', 'midday', 'afternoon', 'evening', 'bedtime', name='take_window_enum'), nullable=False),
    sa.Column('with_food', sa.Boolean(), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('reconstitution', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('storage_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['peptide_id'], ['peptides.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_peptides_user_id'), 'user_peptides', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('user_id', UUID(), nullable=False),
    sa.Column('interaction_mode', sa.Enum('expert', 'advanced', 'automated', 'guided', name='interaction_mode_enum'), nullable=False),
    sa.Column('max_supplements_per_day', sa.Integer(), nullable=True),
    sa.Column('max_tablets_per_day', sa.Integer(), nullable=True),
    sa.Column('max_medications', sa.Integer(), nullable=True),
    sa.Column('exercise_blocks_per_week', sa.Integer(), nullable=True),
    sa.Column('exercise_minutes_per_day', sa.Integer(), nullable=True),
    sa.Column('primary_goals', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('focus_concerns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_ingredients', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('biological_sex', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.drop_index(op.f('ix_interactions_supplement_a_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_supplement_b_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_cycling_schedules_user_id'), table_name='cycling_schedules')
    op.drop_table('cycling_schedules')
    op.add_column('adherence_logs', sa.Column('item_name_snapshot', sa.String(length=255), nullable=True))
    op.add_column('adherence_logs', sa.Column('take_window_snapshot', sa.String(length=40), nullable=True))
    op.add_column('adherence_logs', sa.Column('regimes_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('adherence_logs', sa.Column('dosage_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('adherence_logs', sa.Column('settings_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('protocol_items', sa.Column('user_medication_id', UUID(), nullable=True))
    op.add_column('protocol_items', sa.Column('user_peptide_id', UUID(), nullable=True))
    op.create_foreign_key(None, 'protocol_items', 'user_medications', ['user_medication_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'protocol_items', 'user_peptides', ['user_peptide_id'], ['id'], ondelete='CASCADE')
    op.add_column('protocols', sa.Column('schedule_type', sa.String(length=30), nullable=True))
    op.add_column('protocols', sa.Column('manual_is_active', sa.Boolean(), nullable=False))
    op.add_column('protocols', sa.Column('schedule_start_date', sa.Date(), nullable=True))
    op.add_column('protocols', sa.Column('schedule_end_date', sa.Date(), nullable=True))
    op.add_column('protocols', sa.Column('weeks_of_month', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('supplements', sa.Column('goals', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('supplements', sa.Column('mechanism_tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('supplements', 'category',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('healthy_aging', 'energy_mitochondria', 'brain_mood_stress', 'sleep_recovery', 'cardiovascular', 'glucose_metabolic', 'gut_digestion', 'detox_binding', 'immune_antimicrobial', 'inflammation_antioxidant', 'hormones_fertility', 'musculoskeletal', 'other', name='supplement_category_enum'),
               existing_nullable=False)
    op.add_column('user_supplements', sa.Column('is_out_of_stock', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('location_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'location_name')
    op.drop_column('user_supplements', 'is_out_of_stock')
    op.alter_column('supplements', 'category',
               existing_type=sa.Enum('healthy_aging', 'energy_mitochondria', 'brain_mood_stress', 'sleep_recovery', 'cardiovascular', 'glucose_metabolic', 'gut_digestion', 'detox_binding', 'immune_antimicrobial', 'inflammation_antioxidant', 'hormones_fertility', 'musculoskeletal', 'other', name='supplement_category_enum'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.drop_column('supplements', 'mechanism_tags')
    op.drop_column('supplements', 'goals')
    op.drop_column('protocols', 'weeks_of_month')
    op.drop_column('protocols', 'schedule_end_date')
    op.drop_column('protocols', 'schedule_start_date')
    op.drop_column('protocols', 'manual_is_active')
    op.drop_column('protocols', 'schedule_type')
    op.drop_constraint(None, 'protocol_items', type_='foreignkey')
    op.drop_constraint(None, 'protocol_items', type_='foreignkey')
    op.drop_column('protocol_items', 'user_peptide_id')
    op.drop_column('protocol_items', 'user_medication_id')
    op.drop_column('adherence_logs', 'settings_snapshot')
    op.drop_column('adherence_logs', 'dosage_snapshot')
    op.drop_column('adherence_logs', 'regimes_snapshot')
    op.drop_column('adherence_logs', 'take_window_snapshot')
    op.drop_column('adherence_logs', 'item_name_snapshot')
    op.create_table('cycling_schedules',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('cycle_type', sa.VARCHAR(length=6), nullable=False),
    sa.Column('on_duration_days', sa.INTEGER(), nullable=False),
    sa.Column('off_duration_days', sa.INTEGER(), nullable=False),
    sa.Column('current_phase', sa.VARCHAR(length=10), nullable=False),
    sa.Column('phase_started_at', sa.DATE(), nullable=False),
    sa.Column('next_transition', sa.DATE(), nullable=False),
    sa.Column('taper_schedule', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycling_schedules_user_id'), 'cycling_schedules', ['user_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('supplement_a_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('supplement_b_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('interaction_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=8), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('mechanism', sa.TEXT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ai_confidence', sa.NUMERIC(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplement_a_id'], ['supplements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplement_b_id'], ['supplements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplement_a_id', 'supplement_b_id', name=op.f('uq_interaction_pair'))
    )
    op.create_index(op.f('ix_interactions_supplement_b_id'), 'interactions', ['supplement_b_id'], unique=False)
    op.create_index(op.f('ix_interactions_supplement_a_id'), 'interactions', ['supplement_a_id'], unique=False)
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_peptides_user_id'), table_name='user_peptides')
    op.drop_table('user_peptides')
    op.drop_index(op.f('ix_user_medications_user_id'), table_name='user_medications')
    op.drop_table('user_medications')
    op.drop_index(op.f('ix_peptides_name'), table_name='peptides')
    op.drop_table('peptides')
    op.drop_index(op.f('ix_medications_name'), table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###
