import { StyleSheet } from "react-native";

import { colors } from "@/constants/Colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundSecondary },
  content: { paddingBottom: 32, position: "relative" },
  backdrop: { top: -48, height: 1400 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 8,
  },
  stepIndicator: {
    flexDirection: "row",
    gap: 6,
  },
  stepDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.4)",
  },
  stepDotActive: {
    backgroundColor: colors.primary,
  },
  section: {
    paddingHorizontal: 16,
    gap: 16,
  },
  heroCard: {
    paddingHorizontal: 24,
    paddingVertical: 28,
    borderRadius: 28,
    backgroundColor: "rgba(54,94,130,0.94)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 26,
    elevation: 4,
    overflow: "hidden",
    marginTop: 8,
  },
  heroGlowLarge: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.12)",
    top: -60,
    right: -14,
  },
  heroGlowSmall: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 999,
    backgroundColor: "rgba(255,194,116,0.14)",
    left: -12,
    bottom: -26,
  },
  heroEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.74)",
    marginBottom: 10,
  },
  heroTitle: {
    fontSize: 34,
    fontWeight: "800",
    color: colors.textWhite,
    marginBottom: 10,
  },
  heroSubtitle: {
    fontSize: 16,
    color: "rgba(255,255,255,0.8)",
    lineHeight: 23,
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 2,
    padding: 20,
    marginTop: 8,
  },
  cardEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    color: colors.textMuted,
    marginBottom: 6,
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: colors.grayDark,
    marginBottom: 6,
  },
  cardSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    marginBottom: 16,
  },
  goalGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  goalChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(248,251,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
  },
  goalChipSelected: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.infoBorder,
  },
  goalChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  goalChipTextSelected: {
    color: colors.primaryDarker,
  },
  chipPressed: {
    opacity: 0.94,
    transform: [{ scale: 0.985 }],
  },
  hint: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 12,
    textAlign: "right",
  },
  fieldGroup: {
    marginBottom: 18,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textSecondary,
    marginBottom: 8,
  },
  modeGrid: {
    gap: 10,
  },
  modeCard: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 18,
    backgroundColor: "rgba(248,251,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    gap: 2,
  },
  modeCardSelected: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.infoBorder,
  },
  modeLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.textSecondary,
    marginTop: 4,
  },
  modeLabelSelected: {
    color: colors.primaryDarker,
  },
  modeDescription: {
    fontSize: 12,
    color: colors.textMuted,
    lineHeight: 17,
  },
  inlineRow: {
    flexDirection: "row",
    gap: 14,
  },
  inlineField: {
    flex: 1,
  },
  sexRow: {
    flexDirection: "row",
    gap: 8,
  },
  sexChip: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 14,
    backgroundColor: "rgba(248,251,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
  },
  sexChipSelected: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.infoBorder,
  },
  sexChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  sexChipTextSelected: {
    color: colors.primaryDarker,
  },
  pathGrid: {
    gap: 12,
  },
  pathCard: {
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderRadius: 20,
    backgroundColor: "rgba(248,251,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    gap: 6,
    alignItems: "center",
  },
  pathCardPrimary: {
    backgroundColor: "rgba(54,94,130,0.94)",
    borderColor: "rgba(255,255,255,0.14)",
    paddingVertical: 22,
  },
  pathCardPrimaryTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.textWhite,
  },
  pathCardPrimaryDesc: {
    fontSize: 13,
    color: "rgba(255,255,255,0.78)",
    textAlign: "center",
    lineHeight: 19,
  },
  pathCardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.grayDark,
  },
  pathCardDesc: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 19,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primaryDark,
    paddingVertical: 15,
    borderRadius: 18,
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 3,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "700",
  },
  skipButton: {
    alignItems: "center",
    paddingVertical: 12,
  },
  skipButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textMuted,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  backButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  navRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  navButton: {
    flex: 1,
    marginLeft: 16,
  },
  buttonPressed: {
    transform: [{ scale: 0.992 }],
    opacity: 0.95,
  },
  bottomSpacer: {
    height: 48,
  },
});
