import { StyleSheet } from "react-native";

import { colors } from "@/constants/Colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundSecondary },
  content: { paddingBottom: 28, position: "relative" },
  backdrop: { top: -48, height: 900 },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.backgroundSecondary,
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.76)",
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 4,
  },
  sectionHint: {
    fontSize: 12,
    color: colors.textMuted,
    marginBottom: 14,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  toggleCopy: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  toggleLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  hint: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 8,
    lineHeight: 17,
  },
  windowRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  windowRowDisabled: {
    opacity: 0.5,
  },
  windowToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  windowLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  windowLabelDisabled: {
    color: colors.textMuted,
  },
  timeInput: {
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    color: colors.textPrimary,
    backgroundColor: "rgba(248,251,255,0.84)",
    width: 80,
    textAlign: "center",
    fontWeight: "600",
  },
  offLabel: {
    fontSize: 13,
    color: colors.textMuted,
    fontWeight: "500",
  },
  quietRow: {
    flexDirection: "row",
    gap: 16,
  },
  quietField: {
    flex: 1,
  },
  quietLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textSecondary,
    marginBottom: 6,
  },
  timingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  timingLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  timingInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  smallInput: {
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 14,
    color: colors.textPrimary,
    backgroundColor: "rgba(248,251,255,0.84)",
    width: 52,
    textAlign: "center",
    fontWeight: "600",
  },
  timingUnit: {
    fontSize: 13,
    color: colors.textMuted,
  },
  alertHint: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
    marginLeft: 26,
  },
  primaryButton: {
    marginHorizontal: 16,
    marginTop: 4,
    backgroundColor: colors.primaryDark,
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: "center",
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 3,
  },
  primaryText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: "700",
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.72)",
  },
  secondaryText: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: "700",
  },
  helperText: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 17,
    color: colors.textMuted,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonPressed: {
    transform: [{ scale: 0.992 }],
    opacity: 0.95,
  },
});
