import uuid

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import get_current_user
from app.database import get_session
from app.models.supplement import Supplement
from app.models.user import User
from app.schemas.common import PaginatedResponse
from app.schemas.supplement import SupplementOnboardRequest, SupplementOnboardResponse, SupplementResponse

router = APIRouter(prefix="/supplements", tags=["supplements"])


@router.get("", response_model=PaginatedResponse[SupplementResponse])
async def list_supplements(
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=100),
    search: str | None = None,
    category: str | None = None,
    session: AsyncSession = Depends(get_session),
    _current_user: User = Depends(get_current_user),
):
    base_query = select(Supplement)
    if search:
        base_query = base_query.where(Supplement.name.ilike(f"%{search}%"))
    if category:
        base_query = base_query.where(Supplement.category == category)

    count_result = await session.execute(select(func.count()).select_from(base_query.subquery()))
    total = count_result.scalar_one()

    offset = (page - 1) * page_size
    result = await session.execute(base_query.order_by(Supplement.name).offset(offset).limit(page_size))
    supplements = list(result.scalars().all())

    return PaginatedResponse(
        items=[SupplementResponse.model_validate(s) for s in supplements],
        total=total,
        page=page,
        page_size=page_size,
        has_more=(offset + page_size) < total,
    )


@router.get("/{supplement_id}", response_model=SupplementResponse)
async def get_supplement(
    supplement_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),
    _current_user: User = Depends(get_current_user),
):
    result = await session.execute(select(Supplement).where(Supplement.id == supplement_id))
    supplement = result.scalar_one_or_none()
    if not supplement:
        raise HTTPException(status_code=404, detail="Supplement not found")
    return SupplementResponse.model_validate(supplement)


@router.post("/onboard", response_model=SupplementOnboardResponse, status_code=201)
async def onboard_supplement(
    data: SupplementOnboardRequest,
    session: AsyncSession = Depends(get_session),
    _current_user: User = Depends(get_current_user),
):
    # Check for existing match (case-insensitive)
    result = await session.execute(select(Supplement).where(func.lower(Supplement.name) == data.name.lower()))
    existing = result.scalar_one_or_none()
    if existing:
        status = "ready" if existing.ai_profile else "generating"
        return SupplementOnboardResponse(
            id=existing.id,
            name=existing.name,
            status=status,
            ai_profile=existing.ai_profile,
        )

    # Create new supplement (AI profile will be generated by worker)
    supplement = Supplement(
        name=data.name,
        category=data.category or "other",
        form=data.form,
    )
    session.add(supplement)
    await session.commit()
    await session.refresh(supplement)

    # TODO: Dispatch Celery task for AI onboarding (Phase 2)
    # from app.worker.tasks.ai_onboarding import generate_ai_profile
    # generate_ai_profile.delay(str(supplement.id))

    return SupplementOnboardResponse(
        id=supplement.id,
        name=supplement.name,
        status="generating",
        ai_profile=None,
    )
