import asyncio
import logging
import uuid

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Query
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import get_current_user
from app.database import get_session
from app.models.supplement import Supplement
from app.models.user import User
from app.schemas.common import PaginatedResponse
from app.schemas.supplement import SupplementOnboardRequest, SupplementOnboardResponse, SupplementResponse
from app.services.ai_onboarding import (
    get_ai_unavailable_reason,
    resolve_ai_status,
    run_ai_onboarding_job_sync,
    set_ai_status,
)
from app.services.pagination import paginate, paginated_response
from app.tasks.ai_onboarding import generate_ai_profile

router = APIRouter(prefix="/supplements", tags=["supplements"])
logger = logging.getLogger(__name__)


async def _serialize_supplement(supplement: Supplement) -> SupplementResponse:
    ai_status, ai_error = await resolve_ai_status(supplement)
    return SupplementResponse(
        id=supplement.id,
        name=supplement.name,
        category=supplement.category,
        form=supplement.form,
        description=supplement.description,
        goals=supplement.goals,
        mechanism_tags=supplement.mechanism_tags,
        ai_profile=supplement.ai_profile,
        ai_status=ai_status,
        ai_error=ai_error,
        ai_generated_at=supplement.ai_generated_at,
        is_verified=supplement.is_verified,
    )


def _dispatch_ai_onboarding(supplement_id: uuid.UUID, background_tasks: BackgroundTasks) -> None:
    try:
        generate_ai_profile.delay(str(supplement_id))
    except Exception:
        logger.warning("Celery dispatch failed for supplement %s, using in-process fallback", supplement_id, exc_info=True)
        background_tasks.add_task(run_ai_onboarding_job_sync, str(supplement_id))


@router.get("", response_model=PaginatedResponse[SupplementResponse])
async def list_supplements(
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=100),
    search: str | None = None,
    category: str | None = None,
    session: AsyncSession = Depends(get_session),
    _current_user: User = Depends(get_current_user),
):
    query = select(Supplement).order_by(Supplement.name)
    if search:
        query = query.where(Supplement.name.ilike(f"%{search}%"))
    if category:
        query = query.where(Supplement.category == category)

    rows, total, has_more = await paginate(session, query, page, page_size)
    return paginated_response(
        items=list(await asyncio.gather(*(_serialize_supplement(s) for s in rows))),
        total=total, page=page, page_size=page_size, has_more=has_more,
    )


@router.get("/{supplement_id}", response_model=SupplementResponse)
async def get_supplement(
    supplement_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),
    _current_user: User = Depends(get_current_user),
):
    result = await session.execute(select(Supplement).where(Supplement.id == supplement_id))
    supplement = result.scalar_one_or_none()
    if not supplement:
        raise HTTPException(status_code=404, detail="Supplement not found")
    return await _serialize_supplement(supplement)


@router.post("/onboard", response_model=SupplementOnboardResponse, status_code=201)
async def onboard_supplement(
    data: SupplementOnboardRequest,
    background_tasks: BackgroundTasks,
    session: AsyncSession = Depends(get_session),
    _current_user: User = Depends(get_current_user),
):
    unavailable_reason = get_ai_unavailable_reason()

    # Check for existing match (case-insensitive)
    result = await session.execute(select(Supplement).where(func.lower(Supplement.name) == data.name.lower()))
    existing = result.scalar_one_or_none()
    if existing:
        status, error = await resolve_ai_status(existing)
        if not existing.ai_profile and status != "generating":
            if unavailable_reason:
                await set_ai_status(str(existing.id), "failed", unavailable_reason)
                status, error = "failed", unavailable_reason
            else:
                await set_ai_status(str(existing.id), "generating")
                _dispatch_ai_onboarding(existing.id, background_tasks)
                status, error = "generating", None
        return SupplementOnboardResponse(
            id=existing.id,
            name=existing.name,
            status=status,
            ai_profile=existing.ai_profile,
            ai_error=error,
        )

    # Create new supplement (AI profile will be generated by worker)
    supplement = Supplement(
        name=data.name,
        category=data.category or "other",
        form=data.form,
    )
    session.add(supplement)
    await session.commit()
    await session.refresh(supplement)

    if unavailable_reason:
        await set_ai_status(str(supplement.id), "failed", unavailable_reason)
        return SupplementOnboardResponse(
            id=supplement.id,
            name=supplement.name,
            status="failed",
            ai_profile=None,
            ai_error=unavailable_reason,
        )

    await set_ai_status(str(supplement.id), "generating")
    _dispatch_ai_onboarding(supplement.id, background_tasks)

    return SupplementOnboardResponse(
        id=supplement.id,
        name=supplement.name,
        status="generating",
        ai_profile=None,
        ai_error=None,
    )
