"""Seed data for the exercise catalog (~80 exercises across all categories)."""

EXERCISE_CATALOG = [
    # ─── Compound / Barbell ───────────────────────────────────────────
    {
        "name": "Barbell Bench Press",
        "category": "compound",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Flat barbell bench press — primary horizontal push for chest development.",
        "instructions": "Lie on a flat bench, grip the bar slightly wider than shoulder-width. Unrack, lower to mid-chest, press back up to lockout.",
    },
    {
        "name": "Incline Barbell Bench Press",
        "category": "compound",
        "primary_muscle": "chest",
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Incline press targeting the upper chest and front delts.",
        "instructions": "Set bench to 30-45 degrees. Unrack bar, lower to upper chest, press to lockout.",
    },
    {
        "name": "Barbell Back Squat",
        "category": "compound",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings", "core"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Barbell back squat — foundational lower body compound movement.",
        "instructions": "Bar on upper traps, feet shoulder-width, break at hips and knees, descend to parallel or below, drive up through heels.",
    },
    {
        "name": "Front Squat",
        "category": "compound",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "core"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Front-loaded squat emphasizing quads and core stability.",
        "instructions": "Bar in front rack position, elbows high, descend with upright torso, drive up.",
    },
    {
        "name": "Conventional Deadlift",
        "category": "compound",
        "primary_muscle": "back",
        "secondary_muscles": ["hamstrings", "glutes", "core", "forearms"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Full-body pull from the floor — builds posterior chain and grip strength.",
        "instructions": "Feet hip-width, grip just outside knees, hinge at hips, keep back flat, drive through the floor to lockout.",
    },
    {
        "name": "Sumo Deadlift",
        "category": "compound",
        "primary_muscle": "glutes",
        "secondary_muscles": ["quadriceps", "hamstrings", "back"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Wide-stance deadlift variation emphasizing glutes and inner thighs.",
        "instructions": "Wide stance, toes angled out, grip inside knees, push floor apart as you lift.",
    },
    {
        "name": "Romanian Deadlift",
        "category": "compound",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "back"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Hip-hinge movement targeting hamstrings and glutes.",
        "instructions": "Hold bar at hip height, slight knee bend, hinge at hips pushing them back, lower bar along legs, return to standing.",
    },
    {
        "name": "Overhead Press",
        "category": "compound",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps", "core"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Standing barbell press — builds shoulder strength and stability.",
        "instructions": "Bar at collarbone, grip just outside shoulders, press overhead to lockout, slight lean back at bottom.",
    },
    {
        "name": "Barbell Row",
        "category": "compound",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps", "forearms"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Bent-over barbell row — primary horizontal pull for back thickness.",
        "instructions": "Hinge forward ~45 degrees, pull bar to lower chest/upper abs, squeeze shoulder blades, lower under control.",
    },
    {
        "name": "Pendlay Row",
        "category": "compound",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps", "forearms"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Strict row from the floor each rep — explosive back power.",
        "instructions": "Torso parallel to floor, pull bar explosively from floor to lower chest, lower back to floor each rep.",
    },
    {
        "name": "Hip Thrust",
        "category": "compound",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Barbell hip thrust for maximal glute activation.",
        "instructions": "Upper back on bench, bar over hips, drive hips to full extension, squeeze glutes at top, lower under control.",
    },
    # ─── Compound / Dumbbell ──────────────────────────────────────────
    {
        "name": "Dumbbell Bench Press",
        "category": "compound",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "dumbbell",
        "is_compound": True,
        "description": "Flat dumbbell press — greater range of motion than barbell.",
        "instructions": "Lie flat, press dumbbells up from chest level, lower with control to stretch position.",
    },
    {
        "name": "Dumbbell Shoulder Press",
        "category": "compound",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment": "dumbbell",
        "is_compound": True,
        "description": "Seated or standing dumbbell overhead press.",
        "instructions": "Dumbbells at shoulder height, press overhead to lockout, lower under control.",
    },
    {
        "name": "Dumbbell Row",
        "category": "compound",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps", "forearms"],
        "equipment": "dumbbell",
        "is_compound": True,
        "description": "Single-arm dumbbell row — builds unilateral back strength.",
        "instructions": "One hand on bench, row dumbbell to hip, squeeze shoulder blade, lower under control.",
    },
    {
        "name": "Dumbbell Lunge",
        "category": "compound",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": "dumbbell",
        "is_compound": True,
        "description": "Walking or stationary lunges with dumbbells.",
        "instructions": "Step forward, lower back knee toward floor, front knee over ankle, drive up through front heel.",
    },
    {
        "name": "Dumbbell Romanian Deadlift",
        "category": "compound",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "back"],
        "equipment": "dumbbell",
        "is_compound": True,
        "description": "Dumbbell variation of the RDL for hamstring and glute work.",
        "instructions": "Hold dumbbells at sides, hinge at hips, push hips back, lower dumbbells along legs, return to standing.",
    },
    {
        "name": "Goblet Squat",
        "category": "compound",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "core"],
        "equipment": "dumbbell",
        "is_compound": True,
        "description": "Front-loaded squat holding a dumbbell at chest — great for learning squat pattern.",
        "instructions": "Hold dumbbell vertically at chest, squat between knees, elbows inside knees, drive up.",
    },
    # ─── Isolation / Upper Body ───────────────────────────────────────
    {
        "name": "Barbell Bicep Curl",
        "category": "isolation",
        "primary_muscle": "biceps",
        "secondary_muscles": ["forearms"],
        "equipment": "barbell",
        "is_compound": False,
        "description": "Standing barbell curl for biceps mass.",
        "instructions": "Stand with barbell at arms' length, curl to shoulders without swinging, lower under control.",
    },
    {
        "name": "Dumbbell Bicep Curl",
        "category": "isolation",
        "primary_muscle": "biceps",
        "secondary_muscles": ["forearms"],
        "equipment": "dumbbell",
        "is_compound": False,
        "description": "Classic dumbbell curl — alternating or simultaneous.",
        "instructions": "Curl dumbbells with supinated grip, squeeze at top, lower under control.",
    },
    {
        "name": "Hammer Curl",
        "category": "isolation",
        "primary_muscle": "biceps",
        "secondary_muscles": ["forearms"],
        "equipment": "dumbbell",
        "is_compound": False,
        "description": "Neutral-grip curl targeting brachialis and brachioradialis.",
        "instructions": "Curl dumbbells with neutral (palms facing) grip, squeeze at top.",
    },
    {
        "name": "Preacher Curl",
        "category": "isolation",
        "primary_muscle": "biceps",
        "secondary_muscles": [],
        "equipment": "ez_bar",
        "is_compound": False,
        "description": "Preacher bench curl isolating the biceps with no momentum.",
        "instructions": "Arms on preacher pad, curl EZ bar to top, lower slowly to full extension.",
    },
    {
        "name": "Tricep Pushdown",
        "category": "isolation",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment": "cable",
        "is_compound": False,
        "description": "Cable pushdown for triceps — rope or bar attachment.",
        "instructions": "Elbows at sides, push cable down to lockout, squeeze triceps, return under control.",
    },
    {
        "name": "Skull Crushers",
        "category": "isolation",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment": "ez_bar",
        "is_compound": False,
        "description": "Lying tricep extension — great for long head development.",
        "instructions": "Lie on bench, lower EZ bar to forehead or behind head, extend arms to lockout.",
    },
    {
        "name": "Overhead Tricep Extension",
        "category": "isolation",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "is_compound": False,
        "description": "Overhead dumbbell extension for triceps long head.",
        "instructions": "Hold dumbbell overhead with both hands, lower behind head, extend to lockout.",
    },
    {
        "name": "Lateral Raise",
        "category": "isolation",
        "primary_muscle": "shoulders",
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "is_compound": False,
        "description": "Dumbbell lateral raise for medial deltoid development.",
        "instructions": "Arms at sides, raise dumbbells out to shoulder height, slight bend in elbows, lower slowly.",
    },
    {
        "name": "Cable Lateral Raise",
        "category": "isolation",
        "primary_muscle": "shoulders",
        "secondary_muscles": [],
        "equipment": "cable",
        "is_compound": False,
        "description": "Cable lateral raise — constant tension through full ROM.",
        "instructions": "Stand beside cable, raise arm out to shoulder height, lower under control.",
    },
    {
        "name": "Rear Delt Fly",
        "category": "isolation",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["back"],
        "equipment": "dumbbell",
        "is_compound": False,
        "description": "Bent-over or seated fly for rear deltoid development.",
        "instructions": "Hinge forward, raise dumbbells out to sides squeezing rear delts, lower under control.",
    },
    {
        "name": "Face Pull",
        "category": "isolation",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["back"],
        "equipment": "cable",
        "is_compound": False,
        "description": "Cable face pull for rear delts and rotator cuff health.",
        "instructions": "Rope attachment at face height, pull toward face with elbows high, externally rotate at end.",
    },
    {
        "name": "Cable Fly",
        "category": "isolation",
        "primary_muscle": "chest",
        "secondary_muscles": [],
        "equipment": "cable",
        "is_compound": False,
        "description": "Cable crossover/fly for chest isolation.",
        "instructions": "Cables at high or mid position, bring hands together in arc, squeeze chest, return slowly.",
    },
    {
        "name": "Dumbbell Fly",
        "category": "isolation",
        "primary_muscle": "chest",
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "is_compound": False,
        "description": "Flat or incline dumbbell fly for chest stretch and contraction.",
        "instructions": "Lie on bench, arms wide with slight bend, bring dumbbells together over chest, lower in arc.",
    },
    # ─── Isolation / Lower Body ───────────────────────────────────────
    {
        "name": "Leg Extension",
        "category": "isolation",
        "primary_muscle": "quadriceps",
        "secondary_muscles": [],
        "equipment": "machine",
        "is_compound": False,
        "description": "Machine leg extension — isolates quadriceps.",
        "instructions": "Sit in machine, extend legs to full lockout, squeeze quads, lower under control.",
    },
    {
        "name": "Leg Curl",
        "category": "isolation",
        "primary_muscle": "hamstrings",
        "secondary_muscles": [],
        "equipment": "machine",
        "is_compound": False,
        "description": "Machine leg curl — lying or seated hamstring isolation.",
        "instructions": "Curl weight toward glutes, squeeze hamstrings at top, lower slowly.",
    },
    {
        "name": "Calf Raise",
        "category": "isolation",
        "primary_muscle": "calves",
        "secondary_muscles": [],
        "equipment": "machine",
        "is_compound": False,
        "description": "Standing or seated calf raise.",
        "instructions": "Rise onto toes, squeeze calves at top, lower to full stretch below platform.",
    },
    {
        "name": "Cable Kickback",
        "category": "isolation",
        "primary_muscle": "glutes",
        "secondary_muscles": [],
        "equipment": "cable",
        "is_compound": False,
        "description": "Cable glute kickback for targeted glute activation.",
        "instructions": "Ankle strap on cable, kick leg back squeezing glute, return under control.",
    },
    {
        "name": "Hip Adduction Machine",
        "category": "isolation",
        "primary_muscle": "glutes",
        "secondary_muscles": [],
        "equipment": "machine",
        "is_compound": False,
        "description": "Machine adduction for inner thigh / adductors.",
        "instructions": "Squeeze legs together against pads, hold briefly, return slowly.",
    },
    {
        "name": "Hip Abduction Machine",
        "category": "isolation",
        "primary_muscle": "glutes",
        "secondary_muscles": [],
        "equipment": "machine",
        "is_compound": False,
        "description": "Machine abduction for outer glutes / abductors.",
        "instructions": "Push legs apart against pads, hold briefly, return slowly.",
    },
    # ─── Compound / Machine & Cable ───────────────────────────────────
    {
        "name": "Lat Pulldown",
        "category": "compound",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "cable",
        "is_compound": True,
        "description": "Cable lat pulldown — vertical pull for back width.",
        "instructions": "Wide grip on bar, pull to upper chest, squeeze lats, return slowly.",
    },
    {
        "name": "Seated Cable Row",
        "category": "compound",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps", "forearms"],
        "equipment": "cable",
        "is_compound": True,
        "description": "Seated row — horizontal pull for back thickness.",
        "instructions": "Sit upright, pull handle to torso, squeeze shoulder blades, return under control.",
    },
    {
        "name": "Chest Press Machine",
        "category": "compound",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "machine",
        "is_compound": True,
        "description": "Machine chest press — guided horizontal push.",
        "instructions": "Press handles forward to full extension, lower slowly to stretch position.",
    },
    {
        "name": "Leg Press",
        "category": "compound",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": "machine",
        "is_compound": True,
        "description": "Machine leg press for heavy quad and glute loading.",
        "instructions": "Feet shoulder-width on platform, lower sled until 90 degrees, press to near-lockout.",
    },
    {
        "name": "Hack Squat",
        "category": "compound",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes"],
        "equipment": "machine",
        "is_compound": True,
        "description": "Machine hack squat — quad-dominant squat variation.",
        "instructions": "Back against pad, feet forward on platform, squat down and drive up.",
    },
    {
        "name": "Smith Machine Squat",
        "category": "compound",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": "smith_machine",
        "is_compound": True,
        "description": "Guided squat on Smith machine.",
        "instructions": "Bar on traps, feet slightly forward, squat to parallel, drive up.",
    },
    # ─── Bodyweight ───────────────────────────────────────────────────
    {
        "name": "Pull-Up",
        "category": "bodyweight",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps", "forearms"],
        "equipment": "bodyweight",
        "is_compound": True,
        "description": "Overhand pull-up — builds back width and pulling strength.",
        "instructions": "Hang with overhand grip, pull chin above bar, lower under control.",
    },
    {
        "name": "Chin-Up",
        "category": "bodyweight",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "bodyweight",
        "is_compound": True,
        "description": "Underhand chin-up — more bicep involvement than pull-up.",
        "instructions": "Hang with underhand grip, pull chin above bar, lower under control.",
    },
    {
        "name": "Push-Up",
        "category": "bodyweight",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders", "core"],
        "equipment": "bodyweight",
        "is_compound": True,
        "description": "Classic push-up — foundational pushing movement.",
        "instructions": "Hands shoulder-width, body straight, lower chest to floor, push back up.",
    },
    {
        "name": "Dip",
        "category": "bodyweight",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "bodyweight",
        "is_compound": True,
        "description": "Parallel bar dip — chest and tricep builder.",
        "instructions": "Support on parallel bars, lower until upper arms parallel to floor, press back up.",
    },
    {
        "name": "Inverted Row",
        "category": "bodyweight",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "bodyweight",
        "is_compound": True,
        "description": "Horizontal pulling bodyweight row using a bar at waist height.",
        "instructions": "Hang under bar, body straight, pull chest to bar, lower slowly.",
    },
    {
        "name": "Plank",
        "category": "bodyweight",
        "primary_muscle": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "bodyweight",
        "is_compound": False,
        "description": "Isometric core hold — builds endurance and stability.",
        "instructions": "Forearms and toes on floor, body straight, hold position without sagging.",
    },
    {
        "name": "Hanging Leg Raise",
        "category": "bodyweight",
        "primary_muscle": "core",
        "secondary_muscles": ["forearms"],
        "equipment": "bodyweight",
        "is_compound": False,
        "description": "Hanging from a bar, raise legs to work lower abs.",
        "instructions": "Hang from bar, raise straight legs to parallel or above, lower under control.",
    },
    {
        "name": "Pistol Squat",
        "category": "bodyweight",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "core"],
        "equipment": "bodyweight",
        "is_compound": True,
        "description": "Single-leg squat — advanced unilateral leg exercise.",
        "instructions": "Stand on one leg, extend other forward, squat to full depth, stand back up.",
    },
    {
        "name": "Mountain Climber",
        "category": "bodyweight",
        "primary_muscle": "core",
        "secondary_muscles": ["shoulders", "quadriceps"],
        "equipment": "bodyweight",
        "is_compound": True,
        "description": "Dynamic core exercise with cardio element.",
        "instructions": "Push-up position, alternately drive knees to chest rapidly.",
    },
    {
        "name": "Burpee",
        "category": "bodyweight",
        "primary_muscle": "full_body",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "is_compound": True,
        "description": "Full-body explosive conditioning movement.",
        "instructions": "Squat down, kick feet back to push-up, push-up, jump feet forward, jump up.",
    },
    # ─── Olympic Lifts ────────────────────────────────────────────────
    {
        "name": "Clean and Jerk",
        "category": "olympic",
        "primary_muscle": "full_body",
        "secondary_muscles": ["shoulders", "quadriceps", "back", "glutes"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Olympic lift — clean the bar to shoulders, then jerk overhead.",
        "instructions": "Explosive pull from floor to front rack, dip and drive overhead to lockout.",
    },
    {
        "name": "Snatch",
        "category": "olympic",
        "primary_muscle": "full_body",
        "secondary_muscles": ["shoulders", "back", "quadriceps", "glutes"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Olympic snatch — bar from floor to overhead in one motion.",
        "instructions": "Wide grip, explosive pull, drop under bar into overhead squat, stand up.",
    },
    {
        "name": "Power Clean",
        "category": "olympic",
        "primary_muscle": "full_body",
        "secondary_muscles": ["back", "quadriceps", "shoulders"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Explosive clean caught in partial squat — power development.",
        "instructions": "Start position like deadlift, explosive pull, catch in front rack with partial squat.",
    },
    {
        "name": "Hang Clean",
        "category": "olympic",
        "primary_muscle": "full_body",
        "secondary_muscles": ["back", "quadriceps", "shoulders"],
        "equipment": "barbell",
        "is_compound": True,
        "description": "Clean starting from hang position — emphasis on second pull.",
        "instructions": "Bar at hip or knee height, explosive hip extension, catch in front rack.",
    },
    # ─── Kettlebell ───────────────────────────────────────────────────
    {
        "name": "Kettlebell Swing",
        "category": "compound",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings", "core", "shoulders"],
        "equipment": "kettlebell",
        "is_compound": True,
        "description": "Ballistic hip-hinge movement — builds explosive posterior chain power.",
        "instructions": "Hinge at hips, swing kettlebell between legs, snap hips forward to chest height.",
    },
    {
        "name": "Kettlebell Goblet Squat",
        "category": "compound",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "core"],
        "equipment": "kettlebell",
        "is_compound": True,
        "description": "Front-loaded squat holding kettlebell at chest.",
        "instructions": "Hold kettlebell by horns at chest, squat between knees, drive up.",
    },
    {
        "name": "Turkish Get-Up",
        "category": "compound",
        "primary_muscle": "full_body",
        "secondary_muscles": ["shoulders", "core", "glutes"],
        "equipment": "kettlebell",
        "is_compound": True,
        "description": "Full-body stability movement from lying to standing with weight overhead.",
        "instructions": "Lie down with kettlebell locked out, progress through positions to standing, reverse back down.",
    },
    # ─── Cardio ───────────────────────────────────────────────────────
    {
        "name": "Treadmill Run",
        "category": "cardio",
        "primary_muscle": "cardio",
        "secondary_muscles": ["quadriceps", "hamstrings", "calves"],
        "equipment": "machine",
        "is_compound": False,
        "description": "Treadmill running — steady state or intervals.",
        "instructions": "Set desired speed and incline, maintain form with upright posture.",
    },
    {
        "name": "Stationary Bike",
        "category": "cardio",
        "primary_muscle": "cardio",
        "secondary_muscles": ["quadriceps", "hamstrings"],
        "equipment": "machine",
        "is_compound": False,
        "description": "Upright or recumbent bike — low-impact cardio.",
        "instructions": "Adjust seat height, pedal at desired resistance and cadence.",
    },
    {
        "name": "Rowing Machine",
        "category": "cardio",
        "primary_muscle": "cardio",
        "secondary_muscles": ["back", "biceps", "quadriceps"],
        "equipment": "machine",
        "is_compound": True,
        "description": "Ergometer rowing — full-body cardio and conditioning.",
        "instructions": "Drive with legs first, lean back slightly, pull handle to lower chest, return in reverse order.",
    },
    {
        "name": "Stairmaster",
        "category": "cardio",
        "primary_muscle": "cardio",
        "secondary_muscles": ["quadriceps", "glutes", "calves"],
        "equipment": "machine",
        "is_compound": False,
        "description": "Stair-climbing machine for lower body endurance.",
        "instructions": "Step at steady pace, avoid leaning on handles, maintain upright posture.",
    },
    {
        "name": "Jump Rope",
        "category": "cardio",
        "primary_muscle": "cardio",
        "secondary_muscles": ["calves", "shoulders", "core"],
        "equipment": "none",
        "is_compound": False,
        "description": "Skipping rope — coordination, conditioning, and calf work.",
        "instructions": "Light bounces on balls of feet, wrists drive the rope, keep elbows close to body.",
    },
    {
        "name": "Assault Bike",
        "category": "cardio",
        "primary_muscle": "cardio",
        "secondary_muscles": ["quadriceps", "shoulders"],
        "equipment": "machine",
        "is_compound": True,
        "description": "Air bike with arm cranks — intense full-body cardio.",
        "instructions": "Push and pull arm handles while pedaling, increase effort for more resistance.",
    },
    {
        "name": "Elliptical",
        "category": "cardio",
        "primary_muscle": "cardio",
        "secondary_muscles": ["quadriceps", "glutes"],
        "equipment": "machine",
        "is_compound": False,
        "description": "Elliptical trainer — low-impact cardio.",
        "instructions": "Stride naturally, use handles for upper body engagement, adjust resistance.",
    },
    # ─── Flexibility / Mobility ───────────────────────────────────────
    {
        "name": "Foam Rolling",
        "category": "flexibility",
        "primary_muscle": "full_body",
        "secondary_muscles": [],
        "equipment": "none",
        "is_compound": False,
        "description": "Self-myofascial release using a foam roller.",
        "instructions": "Roll target muscle slowly, pause on tender spots for 20-30 seconds.",
    },
    {
        "name": "Static Stretching",
        "category": "flexibility",
        "primary_muscle": "full_body",
        "secondary_muscles": [],
        "equipment": "none",
        "is_compound": False,
        "description": "Hold stretches for 30-60 seconds per muscle group.",
        "instructions": "Stretch to mild tension, hold without bouncing, breathe deeply.",
    },
    {
        "name": "Dynamic Warm-Up",
        "category": "flexibility",
        "primary_muscle": "full_body",
        "secondary_muscles": [],
        "equipment": "none",
        "is_compound": False,
        "description": "Active mobility drills before training — leg swings, arm circles, hip circles.",
        "instructions": "Perform controlled movements through full range of motion, 10-15 reps per movement.",
    },
    {
        "name": "Yoga Flow",
        "category": "flexibility",
        "primary_muscle": "full_body",
        "secondary_muscles": [],
        "equipment": "none",
        "is_compound": False,
        "description": "Flowing yoga sequence — Sun Salutation or similar vinyasa.",
        "instructions": "Move through poses with breath, maintain alignment, hold each pose 3-5 breaths.",
    },
    {
        "name": "Hip 90/90 Stretch",
        "category": "flexibility",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings"],
        "equipment": "none",
        "is_compound": False,
        "description": "Seated hip mobility drill alternating internal and external rotation.",
        "instructions": "Sit with legs in 90/90 position, rotate between sides, lean forward for deeper stretch.",
    },
    # ─── Plyometric ───────────────────────────────────────────────────
    {
        "name": "Box Jump",
        "category": "plyometric",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "calves"],
        "equipment": "none",
        "is_compound": True,
        "description": "Explosive jump onto a box — builds lower body power.",
        "instructions": "Stand facing box, swing arms and jump, land softly with both feet on box, step down.",
    },
    {
        "name": "Broad Jump",
        "category": "plyometric",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": "none",
        "is_compound": True,
        "description": "Standing long jump for horizontal power development.",
        "instructions": "Swing arms back, explode forward and up, land softly with knees bent.",
    },
    # ─── Resistance Band ──────────────────────────────────────────────
    {
        "name": "Band Pull-Apart",
        "category": "isolation",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["back"],
        "equipment": "resistance_band",
        "is_compound": False,
        "description": "Resistance band pull-apart for rear delt and upper back health.",
        "instructions": "Hold band at chest height, pull apart by squeezing shoulder blades, return slowly.",
    },
    {
        "name": "Banded Hip Thrust",
        "category": "compound",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings"],
        "equipment": "resistance_band",
        "is_compound": True,
        "description": "Hip thrust with band resistance around knees for glute activation.",
        "instructions": "Band above knees, back on bench, drive hips up squeezing glutes, push knees out against band.",
    },
    # ─── Core / Abs ───────────────────────────────────────────────────
    {
        "name": "Cable Woodchop",
        "category": "compound",
        "primary_muscle": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "cable",
        "is_compound": True,
        "description": "Rotational cable movement for obliques and core stability.",
        "instructions": "Cable at high or low position, rotate torso pulling across body, control the return.",
    },
    {
        "name": "Ab Rollout",
        "category": "isolation",
        "primary_muscle": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "none",
        "is_compound": False,
        "description": "Ab wheel or barbell rollout for deep core activation.",
        "instructions": "Kneel, roll wheel forward keeping core braced, extend as far as possible, pull back.",
    },
    {
        "name": "Russian Twist",
        "category": "isolation",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment": "none",
        "is_compound": False,
        "description": "Seated rotational movement for obliques.",
        "instructions": "Sit with knees bent, lean back slightly, rotate torso side to side touching floor.",
    },
    {
        "name": "Dead Bug",
        "category": "bodyweight",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "is_compound": False,
        "description": "Anti-extension core exercise — great for learning bracing.",
        "instructions": "Lie on back, extend opposite arm and leg while keeping lower back pressed to floor.",
    },
    # ─── Trap Bar ─────────────────────────────────────────────────────
    {
        "name": "Trap Bar Deadlift",
        "category": "compound",
        "primary_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings", "back"],
        "equipment": "trap_bar",
        "is_compound": True,
        "description": "Hex/trap bar deadlift — more quad involvement, less lower back stress.",
        "instructions": "Stand inside bar, grip handles, drive up to lockout, lower under control.",
    },
    {
        "name": "Trap Bar Shrug",
        "category": "isolation",
        "primary_muscle": "back",
        "secondary_muscles": ["forearms"],
        "equipment": "trap_bar",
        "is_compound": False,
        "description": "Heavy shrugs using the trap bar for traps development.",
        "instructions": "Hold trap bar at sides, shrug shoulders straight up, squeeze at top, lower slowly.",
    },
]
