"""Extended supplement catalog — lean entries without AI profiles.

AI profiles are generated on-demand when users onboard these supplements.
Each entry provides: name, category, form, goals, mechanism_tags, description.

Categories (body system):
  healthy_aging, energy_mitochondria, brain_mood_stress, sleep_recovery,
  cardiovascular, glucose_metabolic, gut_digestion, detox_binding,
  immune_antimicrobial, inflammation_antioxidant, hormones_fertility,
  musculoskeletal, other

Goal tags (user-facing):
  longevity, cognitive performance, sleep, stress, energy, immunity,
  skin, hair, joint health, gut health, weight management

Mechanism tags (scientific):
  antioxidant, adaptogen, senolytic, anti-inflammatory, neuroprotective,
  NAD+ pathway, gut microbiome modulation, mTOR modulation, AMPK activator,
  mitochondrial support, epigenetic modulator, hormesis
"""

SUPPLEMENT_CATALOG = [
    # ── Healthy Aging ──────────────────────────────────────────────────
    {
        "name": "NMN (Nicotinamide Mononucleotide)",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity", "energy"],
        "mechanism_tags": ["NAD+ pathway"],
        "description": "NAD+ precursor that supports cellular energy production and DNA repair.",
    },
    {
        "name": "Resveratrol",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["antioxidant", "epigenetic modulator"],
        "description": "Polyphenol found in red wine that activates sirtuins and supports cardiovascular health.",
    },
    {
        "name": "Spermidine",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["epigenetic modulator"],
        "description": "Polyamine that induces autophagy and supports cellular renewal.",
    },
    {
        "name": "Urolithin A",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity", "energy"],
        "mechanism_tags": ["mitochondrial support"],
        "description": "Postbiotic metabolite that promotes mitophagy — the recycling of damaged mitochondria.",
    },
    {
        "name": "Fisetin",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["senolytic", "antioxidant"],
        "description": "Flavonoid with potent senolytic activity — clears senescent cells.",
    },
    {
        "name": "Calcium Alpha-Ketoglutarate",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["epigenetic modulator"],
        "description": "Krebs cycle intermediate that has shown lifespan extension in animal models.",
    },
    {
        "name": "NR (Nicotinamide Riboside)",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity", "energy"],
        "mechanism_tags": ["NAD+ pathway"],
        "description": "NAD+ precursor, alternative to NMN, with clinical evidence for raising NAD+ levels.",
    },
    {
        "name": "Ergothioneine",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Amino acid antioxidant concentrated in mitochondria. Nicknamed the 'longevity vitamin'.",
    },
    {
        "name": "Carnosine",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Dipeptide that buffers acid in muscles and prevents protein glycation (AGE formation).",
    },
    {
        "name": "C60 Fullerene",
        "category": "healthy_aging",
        "form": "liquid",
        "goals": ["longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Carbon-60 molecule dissolved in olive oil, investigated for antioxidant and longevity properties.",
    },
    {
        "name": "Oxaloacetate",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity", "energy"],
        "mechanism_tags": ["AMPK activator", "NAD+ pathway"],
        "description": "Krebs cycle intermediate that mimics caloric restriction and boosts NAD+/NADH ratio.",
    },
    {
        "name": "Superoxide Dismutase (SOD)",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Primary antioxidant enzyme. Supplemental forms include Extramel and GliSODin.",
    },
    {
        "name": "StemRegen Release",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": [],
        "description": "Botanical blend designed to support endogenous stem cell release and tissue renewal.",
    },
    {
        "name": "Pterostilbene",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["antioxidant", "epigenetic modulator"],
        "description": "Methylated analog of resveratrol with better bioavailability and sirtuin activation.",
    },
    # ── Energy & Mitochondria ──────────────────────────────────────────
    # NOTE: These are in the original SUPPLEMENTS with full AI profiles:
    # Vitamin D3, Magnesium Glycinate, Omega-3 Fish Oil, Ashwagandha KSM-66,
    # Zinc Picolinate, Creatine Monohydrate, NAC, Vitamin K2 MK-7,
    # Curcumin (Turmeric Extract), Probiotics (Multi-Strain)
    {
        "name": "Coenzyme Q10 (Ubiquinol)",
        "category": "energy_mitochondria",
        "form": "softgel",
        "goals": ["energy", "longevity"],
        "mechanism_tags": ["mitochondrial support", "antioxidant"],
        "description": "Essential cofactor in the mitochondrial electron transport chain. Ubiquinol is the reduced, active form.",
    },
    {
        "name": "PQQ (Pyrroloquinoline Quinone)",
        "category": "energy_mitochondria",
        "form": "capsule",
        "goals": ["energy", "cognitive performance"],
        "mechanism_tags": ["mitochondrial support", "neuroprotective"],
        "description": "Stimulates mitochondrial biogenesis — the creation of new mitochondria.",
    },
    {
        "name": "L-Carnitine",
        "category": "energy_mitochondria",
        "form": "capsule",
        "goals": ["energy", "weight management"],
        "mechanism_tags": ["mitochondrial support"],
        "description": "Shuttles long-chain fatty acids into mitochondria for beta-oxidation. Acetyl-L-carnitine form crosses the blood-brain barrier.",
    },
    {
        "name": "D-Ribose",
        "category": "energy_mitochondria",
        "form": "powder",
        "goals": ["energy"],
        "mechanism_tags": ["mitochondrial support"],
        "description": "Sugar molecule that serves as the backbone for ATP synthesis.",
    },
    {
        "name": "Alpha-Lipoic Acid",
        "category": "energy_mitochondria",
        "form": "capsule",
        "goals": ["energy", "longevity"],
        "mechanism_tags": ["antioxidant", "mitochondrial support"],
        "description": "Universal antioxidant that regenerates vitamins C and E. Cofactor in mitochondrial energy metabolism.",
    },
    {
        "name": "Shilajit",
        "category": "energy_mitochondria",
        "form": "resin",
        "goals": ["energy", "longevity"],
        "mechanism_tags": ["mitochondrial support"],
        "description": "Mineral-rich resin containing fulvic acid. Enhances CoQ10 effectiveness and mitochondrial function.",
    },
    {
        "name": "Cordyceps",
        "category": "energy_mitochondria",
        "form": "capsule",
        "goals": ["energy"],
        "mechanism_tags": ["adaptogen", "mitochondrial support"],
        "description": "Medicinal mushroom that enhances oxygen utilization and ATP production.",
    },
    {
        "name": "Methylated B-Complex",
        "category": "energy_mitochondria",
        "form": "capsule",
        "goals": ["energy"],
        "mechanism_tags": [],
        "description": "Bioactive B vitamins (methylfolate, methylcobalamin, P5P) essential for energy metabolism and methylation.",
    },
    {
        "name": "Iron",
        "category": "energy_mitochondria",
        "form": "capsule",
        "goals": ["energy"],
        "mechanism_tags": [],
        "description": "Essential mineral for oxygen transport (hemoglobin) and mitochondrial electron transport. Only supplement if deficient.",
    },
    {
        "name": "Niacin (Vitamin B3)",
        "category": "energy_mitochondria",
        "form": "capsule",
        "goals": ["energy"],
        "mechanism_tags": ["NAD+ pathway"],
        "description": "NAD+ precursor that supports energy metabolism. Causes flushing at higher doses.",
    },
    {
        "name": "Nicotinamide",
        "category": "energy_mitochondria",
        "form": "capsule",
        "goals": ["energy", "skin"],
        "mechanism_tags": ["NAD+ pathway"],
        "description": "Non-flushing form of vitamin B3. Precursor to NAD+ and supports skin health.",
    },
    # ── Brain, Mood & Stress ───────────────────────────────────────────
    {
        "name": "Lion's Mane",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Medicinal mushroom that stimulates nerve growth factor (NGF) production.",
    },
    {
        "name": "Alpha-GPC",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Bioavailable choline source that crosses the blood-brain barrier and supports acetylcholine synthesis.",
    },
    {
        "name": "L-Theanine",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["stress", "cognitive performance"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Amino acid from green tea that promotes calm focus via alpha brain wave stimulation.",
    },
    {
        "name": "Rhodiola Rosea",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["stress", "energy"],
        "mechanism_tags": ["adaptogen"],
        "description": "Adaptogen that modulates cortisol and enhances mental/physical performance under stress.",
    },
    {
        "name": "Bacopa Monnieri",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["neuroprotective", "adaptogen"],
        "description": "Ayurvedic herb that enhances memory consolidation and reduces anxiety. Benefits take 8-12 weeks.",
    },
    {
        "name": "Phosphatidylserine",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance", "stress"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Phospholipid critical for neuronal membrane integrity. Modulates cortisol response to stress.",
    },
    {
        "name": "5-HTP",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["sleep", "stress"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Direct precursor to serotonin. Supports mood, sleep, and appetite regulation.",
    },
    {
        "name": "SAM-e",
        "category": "brain_mood_stress",
        "form": "tablet",
        "goals": ["stress"],
        "mechanism_tags": ["epigenetic modulator"],
        "description": "Methyl donor involved in neurotransmitter synthesis, DNA methylation, and joint health.",
    },
    {
        "name": "Huperzine A",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Acetylcholinesterase inhibitor from Chinese club moss. Enhances memory and learning.",
    },
    {
        "name": "Ginkgo Biloba",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["neuroprotective", "antioxidant"],
        "description": "Increases cerebral blood flow and provides neuroprotection via flavonoid glycosides.",
    },
    {
        "name": "L-Tyrosine",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance", "stress"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Amino acid precursor to dopamine, norepinephrine, and epinephrine. Supports focus under stress.",
    },
    {
        "name": "Mucuna Pruriens",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["stress"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Natural source of L-DOPA, the direct precursor to dopamine.",
    },
    {
        "name": "GABA",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["stress", "sleep"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Primary inhibitory neurotransmitter. Supplemental form may support relaxation, though blood-brain barrier crossing is debated.",
    },
    {
        "name": "DMAE",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Choline precursor that may support acetylcholine production and membrane fluidity.",
    },
    {
        "name": "Choline",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Essential nutrient for acetylcholine synthesis, cell membrane structure, and methylation.",
    },
    {
        "name": "Phosphatidylcholine",
        "category": "brain_mood_stress",
        "form": "softgel",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Major phospholipid in cell membranes. Supports liver health and choline delivery to the brain.",
    },
    # ── Sleep & Recovery ───────────────────────────────────────────────
    {
        "name": "Melatonin",
        "category": "sleep_recovery",
        "form": "capsule",
        "goals": ["sleep", "longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Endogenous sleep hormone. Low doses (0.3-1mg) are most physiological for circadian entrainment.",
    },
    {
        "name": "Apigenin",
        "category": "sleep_recovery",
        "form": "capsule",
        "goals": ["sleep"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Flavonoid from chamomile, parsley, and celery that binds GABA-A receptors and promotes calm.",
    },
    {
        "name": "Glycine",
        "category": "sleep_recovery",
        "form": "powder",
        "goals": ["sleep"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Amino acid that lowers core body temperature before sleep and acts as an inhibitory neurotransmitter.",
    },
    {
        "name": "Valerian",
        "category": "sleep_recovery",
        "form": "capsule",
        "goals": ["sleep"],
        "mechanism_tags": [],
        "description": "Herbal sedative that increases GABA availability. Often combined with hops or passionflower.",
    },
    {
        "name": "Lemon Balm",
        "category": "sleep_recovery",
        "form": "capsule",
        "goals": ["sleep", "stress"],
        "mechanism_tags": [],
        "description": "Calming herb from the mint family. Inhibits GABA transaminase to raise GABA levels.",
    },
    {
        "name": "Tryptophan",
        "category": "sleep_recovery",
        "form": "capsule",
        "goals": ["sleep"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Essential amino acid precursor to serotonin and melatonin. Supports sleep onset.",
    },
    # ── Cardiovascular ─────────────────────────────────────────────────
    {
        "name": "Omega-3 (EPA/DHA)",
        "category": "cardiovascular",
        "form": "softgel",
        "goals": ["longevity"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Essential fatty acids from fish oil that reduce triglycerides, inflammation, and support endothelial function.",
    },
    {
        "name": "Nattokinase",
        "category": "cardiovascular",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Fibrinolytic enzyme from natto (fermented soybeans) that supports healthy blood clot breakdown.",
    },
    {
        "name": "Vitamin K2 (MK-7)",
        "category": "cardiovascular",
        "form": "softgel",
        "goals": ["longevity", "joint health"],
        "mechanism_tags": [],
        "description": "Directs calcium to bones and teeth, away from arteries. Essential companion to vitamin D3.",
    },
    {
        "name": "Hawthorn",
        "category": "cardiovascular",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": ["antioxidant"],
        "description": "Traditional herb that supports cardiac output, blood pressure, and endothelial function.",
    },
    {
        "name": "Bergamot",
        "category": "cardiovascular",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": ["antioxidant"],
        "description": "Citrus extract with statin-like effects on LDL cholesterol and cardiovascular biomarkers.",
    },
    {
        "name": "OPC Grape Seed Extract",
        "category": "cardiovascular",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Oligomeric proanthocyanidins that support vascular integrity and blood pressure regulation.",
    },
    {
        "name": "Beetroot Juice",
        "category": "cardiovascular",
        "form": "liquid",
        "goals": ["energy"],
        "mechanism_tags": [],
        "description": "Rich in dietary nitrates that convert to nitric oxide, supporting blood flow and exercise performance.",
    },
    {
        "name": "L-Arginine",
        "category": "cardiovascular",
        "form": "powder",
        "goals": ["energy"],
        "mechanism_tags": [],
        "description": "Amino acid substrate for nitric oxide synthase. Supports vasodilation and blood flow.",
    },
    {
        "name": "Terminalia Arjuna",
        "category": "cardiovascular",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": ["antioxidant"],
        "description": "Ayurvedic herb used for cardiac support, with evidence for improving ejection fraction and endothelial function.",
    },
    {
        "name": "Pentadecanoic Acid (C15:0)",
        "category": "cardiovascular",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": [],
        "description": "Odd-chain fatty acid (Fatty15) associated with cardiometabolic health and longevity biomarkers.",
    },
    # ── Glucose & Metabolic ────────────────────────────────────────────
    {
        "name": "Berberine",
        "category": "glucose_metabolic",
        "form": "capsule",
        "goals": ["weight management", "longevity"],
        "mechanism_tags": ["AMPK activator"],
        "description": "Plant alkaloid with metformin-like AMPK activation. Supports blood glucose and lipid profiles.",
    },
    {
        "name": "Cinnamon Extract",
        "category": "glucose_metabolic",
        "form": "capsule",
        "goals": ["weight management"],
        "mechanism_tags": [],
        "description": "Ceylon cinnamon extract that supports insulin sensitivity and glucose uptake.",
    },
    {
        "name": "Chromium",
        "category": "glucose_metabolic",
        "form": "capsule",
        "goals": ["weight management"],
        "mechanism_tags": [],
        "description": "Trace mineral that enhances insulin signaling and glucose transport into cells.",
    },
    {
        "name": "Myo-Inositol",
        "category": "glucose_metabolic",
        "form": "powder",
        "goals": ["weight management", "stress"],
        "mechanism_tags": [],
        "description": "B-vitamin-like compound that supports insulin signaling, ovarian function, and mood.",
    },
    {
        "name": "Apple Cider Vinegar",
        "category": "glucose_metabolic",
        "form": "liquid",
        "goals": ["weight management", "gut health"],
        "mechanism_tags": [],
        "description": "Acetic acid that blunts postprandial glucose spikes and supports digestion.",
    },
    # ── Gut & Digestion ────────────────────────────────────────────────
    {
        "name": "Butyrate",
        "category": "gut_digestion",
        "form": "capsule",
        "goals": ["gut health"],
        "mechanism_tags": ["gut microbiome modulation", "anti-inflammatory"],
        "description": "Short-chain fatty acid that fuels colonocytes and supports intestinal barrier integrity.",
    },
    {
        "name": "Glutamine",
        "category": "gut_digestion",
        "form": "powder",
        "goals": ["gut health"],
        "mechanism_tags": [],
        "description": "Amino acid that serves as primary fuel for intestinal epithelial cells. Supports gut barrier repair.",
    },
    {
        "name": "Psyllium Husk",
        "category": "gut_digestion",
        "form": "powder",
        "goals": ["gut health"],
        "mechanism_tags": ["gut microbiome modulation"],
        "description": "Soluble fiber that forms a gel in the gut, supporting regularity and feeding beneficial bacteria.",
    },
    {
        "name": "Ox Bile",
        "category": "gut_digestion",
        "form": "capsule",
        "goals": ["gut health"],
        "mechanism_tags": [],
        "description": "Supplemental bile salts to support fat digestion, especially for those without a gallbladder.",
    },
    {
        "name": "Betaine HCl",
        "category": "gut_digestion",
        "form": "capsule",
        "goals": ["gut health"],
        "mechanism_tags": [],
        "description": "Supplemental stomach acid for those with low HCl. Supports protein digestion and mineral absorption.",
    },
    {
        "name": "Betaine TMG",
        "category": "gut_digestion",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["epigenetic modulator"],
        "description": "Trimethylglycine — methyl donor that supports homocysteine metabolism and liver function.",
    },
    {
        "name": "Acacia Fiber",
        "category": "gut_digestion",
        "form": "powder",
        "goals": ["gut health"],
        "mechanism_tags": ["gut microbiome modulation"],
        "description": "Prebiotic soluble fiber that feeds beneficial gut bacteria with minimal bloating.",
    },
    {
        "name": "Resistant Starch",
        "category": "gut_digestion",
        "form": "powder",
        "goals": ["gut health", "weight management"],
        "mechanism_tags": ["gut microbiome modulation"],
        "description": "Starch that resists digestion, reaching the colon where bacteria ferment it into butyrate.",
    },
    {
        "name": "Inulin",
        "category": "gut_digestion",
        "form": "powder",
        "goals": ["gut health"],
        "mechanism_tags": ["gut microbiome modulation"],
        "description": "Prebiotic fiber from chicory root that selectively feeds Bifidobacterium species.",
    },
    {
        "name": "Allicin (Garlic Extract)",
        "category": "gut_digestion",
        "form": "capsule",
        "goals": ["immunity", "gut health"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Bioactive compound from garlic with antimicrobial and cardiovascular benefits.",
    },
    {
        "name": "Ginger",
        "category": "gut_digestion",
        "form": "capsule",
        "goals": ["gut health"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Anti-nausea, prokinetic, and anti-inflammatory root. Supports gastric motility.",
    },
    {
        "name": "Daosin",
        "category": "gut_digestion",
        "form": "capsule",
        "goals": ["gut health"],
        "mechanism_tags": [],
        "description": "Supplemental diamine oxidase (DAO) enzyme for histamine intolerance.",
    },
    {
        "name": "Lactospore",
        "category": "gut_digestion",
        "form": "capsule",
        "goals": ["gut health"],
        "mechanism_tags": ["gut microbiome modulation"],
        "description": "Spore-forming probiotic (Bacillus coagulans) that survives stomach acid for reliable gut delivery.",
    },
    # ── Detox & Binding ────────────────────────────────────────────────
    {
        "name": "Modified Citrus Pectin",
        "category": "detox_binding",
        "form": "powder",
        "goals": [],
        "mechanism_tags": [],
        "description": "Binds heavy metals (lead, mercury) and may inhibit galectin-3, a biomarker for fibrosis.",
    },
    {
        "name": "Chlorella",
        "category": "detox_binding",
        "form": "tablet",
        "goals": [],
        "mechanism_tags": ["antioxidant"],
        "description": "Green microalga that binds heavy metals and provides chlorophyll, vitamins, and minerals.",
    },
    {
        "name": "Activated Charcoal",
        "category": "detox_binding",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": [],
        "description": "Broad-spectrum binder of toxins in the GI tract. Take 2+ hours away from supplements and medications.",
    },
    {
        "name": "Zeolite",
        "category": "detox_binding",
        "form": "powder",
        "goals": [],
        "mechanism_tags": [],
        "description": "Microporous mineral that traps heavy metals and mycotoxins via ion exchange in the gut.",
    },
    {
        "name": "Glutathione (Liposomal)",
        "category": "detox_binding",
        "form": "liquid",
        "goals": ["longevity", "skin"],
        "mechanism_tags": ["antioxidant"],
        "description": "Master antioxidant. Liposomal form bypasses gut degradation for better bioavailability.",
    },
    {
        "name": "Milk Thistle",
        "category": "detox_binding",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": ["antioxidant"],
        "description": "Silymarin extract that protects hepatocytes and supports liver regeneration.",
    },
    {
        "name": "TUDCA",
        "category": "detox_binding",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Tauroursodeoxycholic acid — bile salt that supports liver function and reduces ER stress.",
    },
    {
        "name": "Molecular Hydrogen (H2)",
        "category": "detox_binding",
        "form": "tablet",
        "goals": ["longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Dissolved H2 selectively scavenges hydroxyl radicals without affecting beneficial reactive oxygen species.",
    },
    # ── Immune & Antimicrobial ─────────────────────────────────────────
    {
        "name": "Vitamin C",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": ["immunity", "skin"],
        "mechanism_tags": ["antioxidant"],
        "description": "Water-soluble antioxidant essential for immune cell function and collagen synthesis.",
    },
    {
        "name": "Quercetin",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": ["immunity"],
        "mechanism_tags": ["antioxidant", "anti-inflammatory", "senolytic"],
        "description": "Flavonoid with antihistamine, antiviral, and senolytic properties. Zinc ionophore.",
    },
    {
        "name": "Elderberry",
        "category": "immune_antimicrobial",
        "form": "liquid",
        "goals": ["immunity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Rich in anthocyanins with antiviral activity against influenza and other upper respiratory viruses.",
    },
    {
        "name": "Lactoferrin",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": ["immunity", "gut health"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Iron-binding glycoprotein from colostrum with antimicrobial and immune-modulating properties.",
    },
    {
        "name": "Oregano Oil",
        "category": "immune_antimicrobial",
        "form": "softgel",
        "goals": ["immunity"],
        "mechanism_tags": [],
        "description": "Contains carvacrol and thymol — potent antimicrobial compounds effective against bacteria, fungi, and parasites.",
    },
    {
        "name": "Cat's Claw (Uncaria Tomentosa)",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": ["immunity"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Amazonian vine (AC-11) that supports immune function and DNA repair.",
    },
    {
        "name": "Olive Leaf Extract",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": ["immunity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Contains oleuropein with broad antimicrobial and cardiovascular-protective properties.",
    },
    {
        "name": "Artemisinin",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": [],
        "description": "Compound from Artemisia annua (sweet wormwood) with antiparasitic and antimicrobial properties.",
    },
    {
        "name": "Manuka Honey",
        "category": "immune_antimicrobial",
        "form": "liquid",
        "goals": ["immunity", "gut health"],
        "mechanism_tags": [],
        "description": "Medicinal honey with methylglyoxal (MGO) providing unique antibacterial activity.",
    },
    {
        "name": "Black Seed Oil",
        "category": "immune_antimicrobial",
        "form": "softgel",
        "goals": ["immunity"],
        "mechanism_tags": ["anti-inflammatory", "antioxidant"],
        "description": "Nigella sativa seed oil containing thymoquinone. Broad immune and anti-inflammatory support.",
    },
    {
        "name": "Iodine",
        "category": "immune_antimicrobial",
        "form": "liquid",
        "goals": ["immunity"],
        "mechanism_tags": [],
        "description": "Essential for thyroid hormone synthesis and immune defense. Deficiency is common globally.",
    },
    # ── Inflammation & Antioxidant ─────────────────────────────────────
    {
        "name": "Astaxanthin",
        "category": "inflammation_antioxidant",
        "form": "softgel",
        "goals": ["skin", "longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Carotenoid 6,000x more potent than vitamin C as an antioxidant. Protects against UV and oxidative damage.",
    },
    {
        "name": "Sulforaphane (Broccomax)",
        "category": "inflammation_antioxidant",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["hormesis", "anti-inflammatory"],
        "description": "Nrf2 activator from broccoli sprouts. Upregulates phase II detox enzymes and reduces inflammation.",
    },
    {
        "name": "Green Tea Extract (EGCG)",
        "category": "inflammation_antioxidant",
        "form": "capsule",
        "goals": ["longevity", "weight management"],
        "mechanism_tags": ["antioxidant", "AMPK activator"],
        "description": "Catechin-rich extract that supports antioxidant defense, thermogenesis, and AMPK activation.",
    },
    {
        "name": "Boswellia Serrata",
        "category": "inflammation_antioxidant",
        "form": "capsule",
        "goals": ["joint health"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Frankincense extract that inhibits 5-LOX enzyme. Supports joint comfort and gut inflammation.",
    },
    {
        "name": "MSM (Methylsulfonylmethane)",
        "category": "inflammation_antioxidant",
        "form": "powder",
        "goals": ["joint health"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Organic sulfur compound that supports connective tissue, reduces inflammation, and aids detoxification.",
    },
    {
        "name": "Pycnogenol (Pine Bark Extract)",
        "category": "inflammation_antioxidant",
        "form": "capsule",
        "goals": ["skin", "longevity"],
        "mechanism_tags": ["antioxidant", "anti-inflammatory"],
        "description": "Maritime pine bark extract rich in proanthocyanidins. Supports microcirculation and skin health.",
    },
    {
        "name": "Palmitoylethanolamide (PEA)",
        "category": "inflammation_antioxidant",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Endogenous fatty acid amide that modulates inflammation and pain via PPAR-alpha activation.",
    },
    {
        "name": "Rutin",
        "category": "inflammation_antioxidant",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": ["antioxidant", "anti-inflammatory"],
        "description": "Bioflavonoid that strengthens capillaries and supports healthy venous circulation.",
    },
    {
        "name": "Luteolin",
        "category": "inflammation_antioxidant",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["anti-inflammatory", "neuroprotective"],
        "description": "Flavonoid that crosses the blood-brain barrier and inhibits neuroinflammation.",
    },
    {
        "name": "Piperine",
        "category": "inflammation_antioxidant",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": [],
        "description": "Black pepper extract that enhances bioavailability of curcumin, resveratrol, and other compounds.",
    },
    # ── Hormones & Fertility ───────────────────────────────────────────
    {
        "name": "DHEA",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": ["energy", "longevity"],
        "mechanism_tags": [],
        "description": "Precursor hormone to testosterone and estrogen. Levels decline significantly with age.",
    },
    {
        "name": "DIM (Diindolylmethane)",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": [],
        "description": "Cruciferous vegetable metabolite that supports healthy estrogen metabolism (favors 2-OH pathway).",
    },
    {
        "name": "Ashwagandha",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": ["stress", "sleep"],
        "mechanism_tags": ["adaptogen"],
        "description": "Adaptogenic root that reduces cortisol, supports thyroid function, and may boost testosterone.",
    },
    {
        "name": "Tongkat Ali",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": ["energy"],
        "mechanism_tags": ["adaptogen"],
        "description": "Malaysian herb (Eurycoma longifolia) that supports testosterone levels and reduces SHBG.",
    },
    {
        "name": "Maca",
        "category": "hormones_fertility",
        "form": "powder",
        "goals": ["energy"],
        "mechanism_tags": ["adaptogen"],
        "description": "Peruvian root that supports libido, energy, and hormonal balance. Black maca for men, red for women.",
    },
    {
        "name": "Boron",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": ["joint health"],
        "mechanism_tags": [],
        "description": "Trace mineral that supports free testosterone, bone density, and magnesium utilization.",
    },
    {
        "name": "Panax Ginseng",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": ["energy"],
        "mechanism_tags": ["adaptogen"],
        "description": "Adaptogenic root that supports energy, cognitive function, and sexual health via ginsenoside activity.",
    },
    {
        "name": "He Shou Wu (Fo-Ti)",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": ["hair", "longevity"],
        "mechanism_tags": [],
        "description": "Traditional Chinese herb used for hair pigmentation, liver nourishment, and vitality.",
    },
    {
        "name": "Pine Pollen",
        "category": "hormones_fertility",
        "form": "powder",
        "goals": ["energy"],
        "mechanism_tags": [],
        "description": "Natural source of phyto-androgens including DHEA, androsterone, and testosterone.",
    },
    {
        "name": "Fadogia Agrestis",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": [],
        "description": "Nigerian plant that may support LH and testosterone production. Limited human evidence.",
    },
    {
        "name": "Tribulus Terrestris",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": [],
        "description": "Herb traditionally used for libido. Evidence for testosterone boosting is mixed.",
    },
    # ── Musculoskeletal ────────────────────────────────────────────────
    {
        "name": "Collagen Peptides",
        "category": "musculoskeletal",
        "form": "powder",
        "goals": ["skin", "joint health"],
        "mechanism_tags": [],
        "description": "Hydrolyzed collagen providing glycine, proline, and hydroxyproline for connective tissue synthesis.",
    },
    {
        "name": "Glucosamine Sulphate",
        "category": "musculoskeletal",
        "form": "capsule",
        "goals": ["joint health"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Building block for cartilage glycosaminoglycans. Supports joint lubrication and repair.",
    },
    {
        "name": "Chondroitin",
        "category": "musculoskeletal",
        "form": "capsule",
        "goals": ["joint health"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Cartilage component that supports water retention in joints and inhibits degradative enzymes.",
    },
    {
        "name": "Whey Protein",
        "category": "musculoskeletal",
        "form": "powder",
        "goals": ["energy"],
        "mechanism_tags": ["mTOR modulation"],
        "description": "Fast-digesting complete protein rich in leucine. Potent stimulator of muscle protein synthesis.",
    },
    {
        "name": "HMB (Beta-Hydroxy Beta-Methylbutyrate)",
        "category": "musculoskeletal",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": ["mTOR modulation"],
        "description": "Leucine metabolite that reduces muscle protein breakdown and supports recovery.",
    },
    {
        "name": "Beta-Alanine",
        "category": "musculoskeletal",
        "form": "powder",
        "goals": ["energy"],
        "mechanism_tags": [],
        "description": "Precursor to carnosine, which buffers acid in muscles during high-intensity exercise.",
    },
    {
        "name": "L-Citrulline Malate",
        "category": "musculoskeletal",
        "form": "powder",
        "goals": ["energy"],
        "mechanism_tags": [],
        "description": "Converts to arginine, boosting nitric oxide production. Supports blood flow and exercise performance.",
    },
    {
        "name": "Hyaluronic Acid",
        "category": "musculoskeletal",
        "form": "capsule",
        "goals": ["skin", "joint health"],
        "mechanism_tags": [],
        "description": "Glycosaminoglycan that retains water in joints and skin for hydration and cushioning.",
    },
    {
        "name": "Magnesium Taurate",
        "category": "musculoskeletal",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": [],
        "description": "Magnesium chelated with taurine. Supports muscle relaxation and cardiovascular function.",
    },
    {
        "name": "Cissus Quadrangularis",
        "category": "musculoskeletal",
        "form": "capsule",
        "goals": ["joint health"],
        "mechanism_tags": [],
        "description": "Vine extract traditionally used for bone healing and joint support.",
    },
    # ── Skin & Hair (mapped to relevant body systems) ──────────────────
    {
        "name": "Copper Peptides (GHK-Cu)",
        "category": "inflammation_antioxidant",
        "form": "serum",
        "goals": ["skin", "hair"],
        "mechanism_tags": [],
        "description": "Tripeptide-copper complex that stimulates collagen, promotes wound healing, and supports hair follicles.",
    },
    {
        "name": "Biotin",
        "category": "other",
        "form": "capsule",
        "goals": ["hair", "skin"],
        "mechanism_tags": [],
        "description": "B-vitamin (B7) essential for keratin production. Most benefit when deficient.",
    },
    {
        "name": "Selenium",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": ["immunity", "hair"],
        "mechanism_tags": ["antioxidant"],
        "description": "Essential trace mineral for glutathione peroxidase and thyroid hormone conversion (T4 → T3).",
    },
    {
        "name": "Saw Palmetto",
        "category": "hormones_fertility",
        "form": "softgel",
        "goals": ["hair"],
        "mechanism_tags": [],
        "description": "5-alpha-reductase inhibitor that may reduce DHT and support prostate and hair health.",
    },
    # ── Mushroom Complex ───────────────────────────────────────────────
    {
        "name": "Reishi",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": ["immunity", "sleep"],
        "mechanism_tags": ["adaptogen"],
        "description": "Medicinal mushroom (Ganoderma lucidum) that modulates immune function and supports calm.",
    },
    {
        "name": "Chaga",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": ["immunity", "longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Birch-growing mushroom with extremely high ORAC antioxidant score and immune-modulating beta-glucans.",
    },
    {
        "name": "Shiitake / Maitake",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": ["immunity"],
        "mechanism_tags": [],
        "description": "Culinary mushrooms rich in beta-glucans that activate natural killer cells and macrophages.",
    },
    # ── Other / Multi-category ─────────────────────────────────────────
    {
        "name": "Spirulina",
        "category": "other",
        "form": "powder",
        "goals": ["energy", "immunity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Blue-green algae superfood rich in phycocyanin, protein, iron, and B-vitamins.",
    },
    {
        "name": "CBD",
        "category": "other",
        "form": "oil",
        "goals": ["sleep", "stress"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Non-psychoactive cannabinoid that modulates the endocannabinoid system. Supports calm and sleep.",
    },
    {
        "name": "MCT Oil",
        "category": "other",
        "form": "liquid",
        "goals": ["energy", "cognitive performance"],
        "mechanism_tags": ["mitochondrial support"],
        "description": "Medium-chain triglycerides rapidly converted to ketones for brain and body fuel.",
    },
    {
        "name": "Potassium Citrate",
        "category": "other",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": [],
        "description": "Electrolyte that supports muscle function, blood pressure, and acid-base balance.",
    },
    {
        "name": "Copper",
        "category": "other",
        "form": "liquid",
        "goals": ["hair", "energy"],
        "mechanism_tags": [],
        "description": "Essential trace mineral for iron metabolism, melanin production, and mitochondrial function.",
    },
    {
        "name": "Manganese",
        "category": "other",
        "form": "capsule",
        "goals": ["joint health"],
        "mechanism_tags": ["antioxidant"],
        "description": "Trace mineral cofactor for SOD2, bone formation, and cartilage synthesis.",
    },
    {
        "name": "Lithium (Low-Dose)",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance", "longevity"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Trace mineral (orotate form) at low doses supports neuroprotection and mood stability.",
    },
    {
        "name": "Methylene Blue",
        "category": "energy_mitochondria",
        "form": "liquid",
        "goals": ["cognitive performance", "energy"],
        "mechanism_tags": ["mitochondrial support", "neuroprotective"],
        "description": "Electron carrier that can bypass complex I/III dysfunction in the mitochondrial electron transport chain.",
    },
    {
        "name": "Saffron",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["stress"],
        "mechanism_tags": ["neuroprotective", "antioxidant"],
        "description": "Spice extract with evidence for mood support comparable to low-dose SSRIs. Contains crocin and safranal.",
    },
    {
        "name": "Holy Basil (Tulsi)",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["stress"],
        "mechanism_tags": ["adaptogen"],
        "description": "Adaptogenic herb from Ayurveda that modulates cortisol and supports stress resilience.",
    },
    {
        "name": "Sage",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["neuroprotective"],
        "description": "Herb that inhibits acetylcholinesterase and supports memory. Traditional use for cognitive decline.",
    },
    {
        "name": "Astragalus",
        "category": "healthy_aging",
        "form": "capsule",
        "goals": ["longevity", "immunity"],
        "mechanism_tags": [],
        "description": "Adaptogenic root that activates telomerase (TA-65 derived from it) and supports immune function.",
    },
    {
        "name": "Omega-7",
        "category": "other",
        "form": "softgel",
        "goals": ["skin", "gut health"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Palmitoleic acid (from sea buckthorn) that supports mucosal membrane health and skin hydration.",
    },
    {
        "name": "Vitamin A (Retinol)",
        "category": "immune_antimicrobial",
        "form": "softgel",
        "goals": ["immunity", "skin"],
        "mechanism_tags": [],
        "description": "Fat-soluble vitamin essential for vision, immune function, and epithelial cell differentiation.",
    },
    {
        "name": "Vitamin E (Mixed Tocopherols)",
        "category": "inflammation_antioxidant",
        "form": "softgel",
        "goals": ["skin", "longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Fat-soluble antioxidant that protects cell membranes from lipid peroxidation.",
    },
    {
        "name": "Carotenoids Complex",
        "category": "inflammation_antioxidant",
        "form": "softgel",
        "goals": ["skin", "immunity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Blend of lutein, zeaxanthin, beta-carotene from natural sources. Supports eye and skin health.",
    },
    {
        "name": "Chlorogenic Acid (Coffee Extract)",
        "category": "glucose_metabolic",
        "form": "capsule",
        "goals": ["weight management", "energy"],
        "mechanism_tags": ["AMPK activator", "antioxidant"],
        "description": "Polyphenol from green coffee that modulates glucose absorption and supports metabolic health.",
    },
    {
        "name": "L-Lysine",
        "category": "immune_antimicrobial",
        "form": "capsule",
        "goals": ["immunity", "skin"],
        "mechanism_tags": [],
        "description": "Essential amino acid that inhibits herpes simplex replication and supports collagen synthesis.",
    },
    {
        "name": "D-Mannose",
        "category": "immune_antimicrobial",
        "form": "powder",
        "goals": [],
        "mechanism_tags": [],
        "description": "Simple sugar that prevents E. coli adhesion to urinary tract walls. Used for UTI prevention.",
    },
    {
        "name": "Matcha",
        "category": "brain_mood_stress",
        "form": "powder",
        "goals": ["cognitive performance", "energy"],
        "mechanism_tags": ["antioxidant", "neuroprotective"],
        "description": "Whole green tea leaf providing L-theanine + caffeine synergy with high catechin content.",
    },
    {
        "name": "Rosemary",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": ["antioxidant", "neuroprotective"],
        "description": "Contains carnosic acid and rosmarinic acid. Supports memory and neuroprotection via Nrf2 activation.",
    },
    {
        "name": "St. John's Wort",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["stress"],
        "mechanism_tags": [],
        "description": "Herb with evidence for mild-to-moderate depression. Significant drug interactions — check before combining.",
    },
    {
        "name": "Sodium Bicarbonate",
        "category": "other",
        "form": "powder",
        "goals": ["energy"],
        "mechanism_tags": [],
        "description": "Alkaline buffer used to delay fatigue during high-intensity exercise by neutralizing lactic acid.",
    },
    {
        "name": "Trehalose",
        "category": "healthy_aging",
        "form": "powder",
        "goals": ["longevity"],
        "mechanism_tags": [],
        "description": "Disaccharide that induces autophagy via TFEB activation. Protects proteins from misfolding.",
    },
    {
        "name": "Delphinidin",
        "category": "inflammation_antioxidant",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["antioxidant", "senolytic"],
        "description": "Anthocyanin from dark berries with emerging evidence for senolytic and anti-inflammatory activity.",
    },
    {
        "name": "Kaempferol",
        "category": "inflammation_antioxidant",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["antioxidant", "senolytic"],
        "description": "Flavonoid found in broccoli, kale, and tea with senolytic and anti-inflammatory properties.",
    },
    {
        "name": "Genistein",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Soy isoflavone that acts as a phytoestrogen and tyrosine kinase inhibitor.",
    },
    {
        "name": "Oleoylethanolamide (OEA)",
        "category": "glucose_metabolic",
        "form": "capsule",
        "goals": ["weight management"],
        "mechanism_tags": [],
        "description": "Endogenous lipid that activates PPAR-alpha, promoting satiety and fatty acid oxidation.",
    },
    {
        "name": "Cistanche",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": ["energy", "longevity"],
        "mechanism_tags": ["adaptogen"],
        "description": "Desert plant used in traditional Chinese medicine for vitality, testosterone support, and brain health.",
    },
    {
        "name": "Lumbrokinase",
        "category": "cardiovascular",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": [],
        "description": "Fibrinolytic enzyme from earthworms. Stronger than nattokinase for supporting healthy coagulation.",
    },
    {
        "name": "Proferrin",
        "category": "other",
        "form": "tablet",
        "goals": ["energy"],
        "mechanism_tags": [],
        "description": "Heme iron polypeptide with higher absorption than standard iron supplements and fewer GI side effects.",
    },
    {
        "name": "Flaxseed Oil (ALA)",
        "category": "inflammation_antioxidant",
        "form": "softgel",
        "goals": [],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Plant-based omega-3 (alpha-linolenic acid). Partial conversion to EPA/DHA in the body.",
    },
    {
        "name": "Phosphatidylethanolamine",
        "category": "brain_mood_stress",
        "form": "capsule",
        "goals": ["cognitive performance"],
        "mechanism_tags": [],
        "description": "Phospholipid essential for mitochondrial membrane structure and autophagy signaling.",
    },
    {
        "name": "1-MNA",
        "category": "cardiovascular",
        "form": "capsule",
        "goals": ["longevity"],
        "mechanism_tags": ["anti-inflammatory"],
        "description": "Methylated niacin metabolite with anti-inflammatory and anti-thrombotic properties.",
    },
    {
        "name": "Lycopene",
        "category": "inflammation_antioxidant",
        "form": "softgel",
        "goals": ["skin", "longevity"],
        "mechanism_tags": ["antioxidant"],
        "description": "Red carotenoid from tomatoes with potent antioxidant activity. Supports prostate and cardiovascular health.",
    },
    {
        "name": "Indole-3-Carbinol",
        "category": "hormones_fertility",
        "form": "capsule",
        "goals": [],
        "mechanism_tags": [],
        "description": "Cruciferous vegetable compound that supports estrogen metabolism. Precursor to DIM.",
    },
]
